export interface Journal {
  name: string;
  publisher: string;
  quartile: 'Q1' | 'Q2' | 'Q3' | 'Q4';
  accessType: 'Open Access' | 'Subscription' | 'Hybrid';
  apc: number | null; 
  impactFactor: number;
  indexing: string[]; 
  reviewTimeWeeks: string; 
  publicationTimeWeeks: string; 
  latexTemplateUrl: string;
  homeUrl: string;
  domains: string[]; 
  sjrScore: number;
  keywords: string[];
  scopeText: string;
  minRecommendedScore: number;
  methodologyFocus: string[];
}

export const JOURNAL_DB: Journal[] = [
  // --- Computer Science / AI / ML / CV ---
  {
    name: "IEEE Transactions on Pattern Analysis and Machine Intelligence",
    publisher: "IEEE",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2150,
    impactFactor: 23.6,
    indexing: ["Scopus", "IEEE Xplore", "Web of Science", "PubMed"],
    reviewTimeWeeks: "12-20",
    publicationTimeWeeks: "20-30",
    latexTemplateUrl: "https://template-selector.ieee.org/",
    homeUrl: "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=34",
    domains: ["Computer Science", "Artificial Intelligence", "Computer Vision"],
    sjrScore: 7.8,
    keywords: ["computer vision", "pattern recognition", "machine learning", "deep learning", "image analysis", "neural networks"],
    scopeText: "Publishes high-quality, peer-reviewed articles on all aspects of computer vision, image processing, pattern recognition, and machine learning architectures.",
    minRecommendedScore: 85,
    methodologyFocus: ["experimental", "theoretical", "quantitative"]
  },
  {
    name: "Journal of Machine Learning Research",
    publisher: "Microtome Publishing",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 0,
    impactFactor: 5.1,
    indexing: ["Scopus", "Web of Science", "DBLP"],
    reviewTimeWeeks: "12-24",
    publicationTimeWeeks: "24-48",
    latexTemplateUrl: "https://www.jmlr.org/format/format.html",
    homeUrl: "https://www.jmlr.org/",
    domains: ["Computer Science", "Machine Learning", "Artificial Intelligence"],
    sjrScore: 4.5,
    keywords: ["machine learning", "statistical learning", "optimization", "reinforcement learning", "neural networks", "generalization theory"],
    scopeText: "Provides an international forum for the electronic publication of high-quality scholarly articles in all areas of machine learning and statistical foundations.",
    minRecommendedScore: 80,
    methodologyFocus: ["theoretical", "experimental", "algorithmic"]
  },
  {
    name: "Expert Systems with Applications",
    publisher: "Elsevier",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2980,
    impactFactor: 8.5,
    indexing: ["Scopus", "Web of Science", "DBLP"],
    reviewTimeWeeks: "8-12",
    publicationTimeWeeks: "12-16",
    latexTemplateUrl: "https://www.elsevier.com/journals/expert-systems-with-applications/0957-4174/guide-for-authors",
    homeUrl: "https://www.sciencedirect.com/journal/expert-systems-with-applications",
    domains: ["Computer Science", "Artificial Intelligence", "Information Systems"],
    sjrScore: 2.1,
    keywords: ["expert systems", "knowledge engineering", "applied artificial intelligence", "decision support systems", "data mining", "predictive analytics"],
    scopeText: "Focuses on publishing high-quality papers design, development, testing, implementation, and management of expert systems and applied AI.",
    minRecommendedScore: 70,
    methodologyFocus: ["applied", "experimental", "case-study"]
  },
  {
    name: "Pattern Recognition",
    publisher: "Elsevier",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3240,
    impactFactor: 8.0,
    indexing: ["Scopus", "Web of Science", "DBLP"],
    reviewTimeWeeks: "10-14",
    publicationTimeWeeks: "14-20",
    latexTemplateUrl: "https://www.elsevier.com/journals/pattern-recognition/0031-3203/guide-for-authors",
    homeUrl: "https://www.sciencedirect.com/journal/pattern-recognition",
    domains: ["Computer Science", "Computer Vision", "Artificial Intelligence"],
    sjrScore: 2.3,
    keywords: ["pattern recognition", "feature extraction", "image segmentation", "classification", "clustering", "computer vision"],
    scopeText: "Welcomes research papers representing major advances on the recognition of patterns, object categorization, and classification methods.",
    minRecommendedScore: 75,
    methodologyFocus: ["experimental", "theoretical"]
  },
  {
    name: "International Journal of Computer Vision",
    publisher: "Springer",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3490,
    impactFactor: 11.6,
    indexing: ["Scopus", "Web of Science", "DBLP"],
    reviewTimeWeeks: "12-18",
    publicationTimeWeeks: "18-24",
    latexTemplateUrl: "https://www.springer.com/journal/11263/submission-guidelines",
    homeUrl: "https://www.springer.com/journal/11263",
    domains: ["Computer Science", "Computer Vision", "Artificial Intelligence"],
    sjrScore: 4.1,
    keywords: ["computer vision", "3d reconstruction", "motion analysis", "object detection", "image synthesis", "scene understanding"],
    scopeText: "Publishes high-quality, comprehensive papers on the mathematical and computational foundations of computer vision and image interpretation.",
    minRecommendedScore: 82,
    methodologyFocus: ["theoretical", "experimental"]
  },
  {
    name: "Neural Networks",
    publisher: "Elsevier",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2850,
    impactFactor: 6.0,
    indexing: ["Scopus", "Web of Science", "PubMed"],
    reviewTimeWeeks: "8-12",
    publicationTimeWeeks: "12-18",
    latexTemplateUrl: "https://www.elsevier.com/journals/neural-networks/0893-6080/guide-for-authors",
    homeUrl: "https://www.sciencedirect.com/journal/neural-networks",
    domains: ["Computer Science", "Artificial Intelligence", "Cognitive Science"],
    sjrScore: 1.8,
    keywords: ["neural networks", "deep learning", "neuroscience", "cognitive modelling", "associative memory", "unsupervised learning"],
    scopeText: "Presents original research on the modeling of brain behavior and the design of artificial neural network systems across disciplines.",
    minRecommendedScore: 72,
    methodologyFocus: ["theoretical", "experimental", "computational"]
  },
  {
    name: "IEEE Transactions on Neural Networks and Learning Systems",
    publisher: "IEEE",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2150,
    impactFactor: 10.4,
    indexing: ["Scopus", "IEEE Xplore", "Web of Science", "PubMed"],
    reviewTimeWeeks: "10-16",
    publicationTimeWeeks: "16-24",
    latexTemplateUrl: "https://template-selector.ieee.org/",
    homeUrl: "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5962385",
    domains: ["Computer Science", "Artificial Intelligence", "Machine Learning"],
    sjrScore: 3.2,
    keywords: ["neural networks", "learning systems", "adaptive control", "deep learning", "supervised learning", "system identification"],
    scopeText: "Focuses on the theory, design, and applications of neural networks and related learning systems including mathematical and algorithmic advances.",
    minRecommendedScore: 80,
    methodologyFocus: ["theoretical", "experimental"]
  },
  {
    name: "IEEE Transactions on Image Processing",
    publisher: "IEEE",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2150,
    impactFactor: 10.8,
    indexing: ["Scopus", "IEEE Xplore", "Web of Science"],
    reviewTimeWeeks: "10-15",
    publicationTimeWeeks: "16-22",
    latexTemplateUrl: "https://template-selector.ieee.org/",
    homeUrl: "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=83",
    domains: ["Computer Science", "Computer Vision", "Signal Processing"],
    sjrScore: 2.9,
    keywords: ["image processing", "image restoration", "compression", "reconstruction", "filtering", "segmentation", "video analysis"],
    scopeText: "Covers novel theories, algorithms, and architectures for image and video processing, sensing, representation, and restoration.",
    minRecommendedScore: 78,
    methodologyFocus: ["experimental", "theoretical", "quantitative"]
  },
  {
    name: "Artificial Intelligence Journal",
    publisher: "Elsevier",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2950,
    impactFactor: 7.5,
    indexing: ["Scopus", "Web of Science", "DBLP"],
    reviewTimeWeeks: "12-20",
    publicationTimeWeeks: "18-26",
    latexTemplateUrl: "https://www.elsevier.com/journals/artificial-intelligence/0004-3702/guide-for-authors",
    homeUrl: "https://www.sciencedirect.com/journal/artificial-intelligence",
    domains: ["Computer Science", "Artificial Intelligence"],
    sjrScore: 2.7,
    keywords: ["artificial intelligence", "knowledge representation", "planning", "heuristics", "automated reasoning", "natural language understanding"],
    scopeText: "Welcomes articles on broad aspects of artificial intelligence, including classical reasoning, search algorithms, multi-agent systems, and cognitive models.",
    minRecommendedScore: 80,
    methodologyFocus: ["theoretical", "algorithmic"]
  },
  {
    name: "ACM Transactions on Graphics",
    publisher: "ACM",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 1700,
    impactFactor: 6.2,
    indexing: ["Scopus", "ACM Digital Library", "Web of Science"],
    reviewTimeWeeks: "12-16",
    publicationTimeWeeks: "16-24",
    latexTemplateUrl: "https://www.acm.org/publications/authors/templates",
    homeUrl: "https://dl.acm.org/journal/tog",
    domains: ["Computer Science", "Computer Graphics", "Computer Vision"],
    sjrScore: 4.8,
    keywords: ["computer graphics", "rendering", "physical simulation", "geometric modeling", "animation", "computational photography"],
    scopeText: "The premier journal in computer graphics, covering visual computing, animation, rendering, modeling, and digital art techniques.",
    minRecommendedScore: 85,
    methodologyFocus: ["experimental", "theoretical", "computational"]
  },

  // --- Medicine / Public Health / Clinical ---
  {
    name: "The Lancet",
    publisher: "Elsevier",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 5000,
    impactFactor: 168.9,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "2-4",
    publicationTimeWeeks: "4-8",
    latexTemplateUrl: "https://www.thelancet.com/journals/lancet/information-for-authors",
    homeUrl: "https://www.thelancet.com/",
    domains: ["Medicine", "Public Health"],
    sjrScore: 20.1,
    keywords: ["clinical trials", "global health", "epidemiology", "infectious diseases", "oncology", "public health policy"],
    scopeText: "Publishes high-impact medical research, clinical trials, reviews, and opinion pieces affecting global human health and medicine.",
    minRecommendedScore: 92,
    methodologyFocus: ["clinical-trial", "quantitative", "epidemiological"]
  },
  {
    name: "New England Journal of Medicine",
    publisher: "Massachusetts Medical Society",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3500,
    impactFactor: 158.5,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "2-3",
    publicationTimeWeeks: "3-6",
    latexTemplateUrl: "https://www.nejm.org/author-center",
    homeUrl: "https://www.nejm.org/",
    domains: ["Medicine", "Clinical Medicine"],
    sjrScore: 25.4,
    keywords: ["clinical trial", "cardiology", "oncology", "immunology", "pediatrics", "internal medicine"],
    scopeText: "Provides high-quality, peer-reviewed clinical research and editorial opinions to the global medical community.",
    minRecommendedScore: 95,
    methodologyFocus: ["clinical-trial", "randomized-control", "observational"]
  },
  {
    name: "JAMA: Journal of the American Medical Association",
    publisher: "American Medical Association",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3000,
    impactFactor: 120.7,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "3-5",
    publicationTimeWeeks: "6-10",
    latexTemplateUrl: "https://jamanetwork.com/journals/jama/pages/instructions-for-authors",
    homeUrl: "https://jamanetwork.com/journals/jama",
    domains: ["Medicine", "Public Health"],
    sjrScore: 18.2,
    keywords: ["internal medicine", "clinical trials", "health policy", "epidemiology", "preventive medicine"],
    scopeText: "Promotes the science and art of medicine and the betterment of public health through clinical research and reviews.",
    minRecommendedScore: 90,
    methodologyFocus: ["clinical-trial", "meta-analysis", "quantitative"]
  },
  {
    name: "The BMJ",
    publisher: "BMJ Group",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 4000,
    impactFactor: 93.3,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "4-6",
    publicationTimeWeeks: "6-12",
    latexTemplateUrl: "https://www.bmj.com/about-bmj/resources-authors",
    homeUrl: "https://www.bmj.com/",
    domains: ["Medicine", "Public Health", "Clinical Medicine"],
    sjrScore: 12.3,
    keywords: ["evidence-based medicine", "public health", "primary care", "epidemiology", "clinical practice guidelines"],
    scopeText: "An open-access medical journal focusing on improving medical practice and health policies worldwide through clinical research.",
    minRecommendedScore: 88,
    methodologyFocus: ["clinical-trial", "observational", "qualitative"]
  },
  {
    name: "Annals of Internal Medicine",
    publisher: "American College of Physicians",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3500,
    impactFactor: 39.2,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "4-8",
    publicationTimeWeeks: "8-12",
    latexTemplateUrl: "https://www.acponline.org/clinical-information/journals-publications/annals-of-internal-medicine/author-information",
    homeUrl: "https://www.acpjournals.org/journal/aim",
    domains: ["Medicine", "Clinical Medicine"],
    sjrScore: 8.5,
    keywords: ["internal medicine", "cardiology", "gastroenterology", "endocrinology", "pulmonology", "clinical reviews"],
    scopeText: "Focuses on clinical research and practice updates in internal medicine and its subspecialties.",
    minRecommendedScore: 85,
    methodologyFocus: ["clinical-trial", "quantitative", "review"]
  },
  {
    name: "Lancet Public Health",
    publisher: "Elsevier",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 4500,
    impactFactor: 50.2,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "3-5",
    publicationTimeWeeks: "6-10",
    latexTemplateUrl: "https://www.thelancet.com/journals/lanpub/information-for-authors",
    homeUrl: "https://www.thelancet.com/journals/lanpub/home",
    domains: ["Medicine", "Public Health"],
    sjrScore: 11.2,
    keywords: ["health equity", "epidemiology", "global health policies", "health systems", "environmental health"],
    scopeText: "Dedicated to publishing high-impact research, advocacy, and analyses that drive public health policies internationally.",
    minRecommendedScore: 82,
    methodologyFocus: ["epidemiological", "quantitative", "policy-analysis"]
  },
  {
    name: "Journal of Clinical Medicine",
    publisher: "MDPI",
    quartile: "Q2",
    accessType: "Open Access",
    apc: 2600,
    impactFactor: 3.9,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "3-4",
    publicationTimeWeeks: "4-6",
    latexTemplateUrl: "https://www.mdpi.com/journal/jcm/instructions",
    homeUrl: "https://www.mdpi.com/journal/jcm",
    domains: ["Medicine", "Clinical Medicine"],
    sjrScore: 0.9,
    keywords: ["cardiology", "neurology", "orthopedics", "oncology", "clinical trials", "diagnostics"],
    scopeText: "An international scientific open access journal providing a platform for advances in clinical medicine and diagnosis.",
    minRecommendedScore: 60,
    methodologyFocus: ["experimental", "case-study", "clinical-trial"]
  },
  {
    name: "PLOS Medicine",
    publisher: "PLOS",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 5300,
    impactFactor: 15.8,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-8",
    publicationTimeWeeks: "8-14",
    latexTemplateUrl: "https://journals.plos.org/plosmedicine/s/submission-guidelines",
    homeUrl: "https://journals.plos.org/plosmedicine/",
    domains: ["Medicine", "Public Health"],
    sjrScore: 4.8,
    keywords: ["infectious diseases", "cardiovascular health", "maternal health", "epidemiology", "clinical trials"],
    scopeText: "Focuses on major global health issues, epidemiology, clinical trials, and medical interventions with a focus on open science.",
    minRecommendedScore: 78,
    methodologyFocus: ["epidemiological", "clinical-trial", "quantitative"]
  },
  {
    name: "BMC Medicine",
    publisher: "BioMed Central",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 3790,
    impactFactor: 9.3,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-10",
    publicationTimeWeeks: "8-16",
    latexTemplateUrl: "https://bmcmedprinciples.biomedcentral.com/submission-guidelines",
    homeUrl: "https://bmcmedicine.biomedcentral.com/",
    domains: ["Medicine", "Clinical Medicine", "Public Health"],
    sjrScore: 2.8,
    keywords: ["translational medicine", "clinical trials", "biomedical ethics", "personalized medicine"],
    scopeText: "Publishes papers in all areas of clinical medicine, translational research, clinical trials, and public health policy.",
    minRecommendedScore: 74,
    methodologyFocus: ["experimental", "clinical-trial", "quantitative"]
  },

  // --- Biology / Life Sciences / Genomics ---
  {
    name: "Cell",
    publisher: "Cell Press",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 9900,
    impactFactor: 66.8,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "4-8",
    publicationTimeWeeks: "8-16",
    latexTemplateUrl: "https://www.cell.com/cell/authors",
    homeUrl: "https://www.cell.com/",
    domains: ["Biology", "Life Sciences", "Biochemistry"],
    sjrScore: 18.9,
    keywords: ["cell biology", "molecular biology", "immunology", "stem cells", "neuroscience", "cancer biology"],
    scopeText: "Publishes high-impact findings in molecular biology, cell biology, genetics, developmental biology, and immunology.",
    minRecommendedScore: 92,
    methodologyFocus: ["experimental", "molecular-assay"]
  },
  {
    name: "Nature Biotechnology",
    publisher: "Nature Portfolio",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 11000,
    impactFactor: 46.9,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-10",
    publicationTimeWeeks: "12-20",
    latexTemplateUrl: "https://www.nature.com/nbt/authors",
    homeUrl: "https://www.nature.com/nbt/",
    domains: ["Biology", "Life Sciences", "Biotechnology", "Genomics"],
    sjrScore: 15.1,
    keywords: ["biotechnology", "gene editing", "crispr", "synthetic biology", "nanotechnology", "biomedical engineering"],
    scopeText: "Focuses on commercial, therapeutic, and industrial applications of biotechnology and genetic engineering.",
    minRecommendedScore: 90,
    methodologyFocus: ["experimental", "applied", "computational"]
  },
  {
    name: "Genome Biology",
    publisher: "BioMed Central",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 4390,
    impactFactor: 12.3,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-8",
    publicationTimeWeeks: "8-12",
    latexTemplateUrl: "https://genomebiology.biomedcentral.com/submission-guidelines",
    homeUrl: "https://genomebiology.biomedcentral.com/",
    domains: ["Biology", "Genomics", "Bioinformatics"],
    sjrScore: 6.4,
    keywords: ["genomics", "transcriptomics", "epigenomics", "single-cell sequencing", "bioinformatics", "metagenomics"],
    scopeText: "Focuses on genomic and post-genomic biology, including sequencing tech, epigenetics, bioinformatics, and systems biology.",
    minRecommendedScore: 82,
    methodologyFocus: ["computational", "experimental", "data-analysis"]
  },
  {
    name: "Nucleic Acids Research",
    publisher: "Oxford University Press",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 3200,
    impactFactor: 14.9,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "4-6",
    publicationTimeWeeks: "6-10",
    latexTemplateUrl: "https://academic.oup.com/nar/pages/General_Instructions",
    homeUrl: "https://academic.oup.com/nar",
    domains: ["Biology", "Biochemistry", "Molecular Biology"],
    sjrScore: 5.8,
    keywords: ["rna", "dna", "chromatin", "transcription", "replication", "computational biology"],
    scopeText: "Publishes research on the physical, chemical, and biological aspects of nucleic acids and proteins in nucleic acid metabolism.",
    minRecommendedScore: 80,
    methodologyFocus: ["experimental", "computational", "structural"]
  },
  {
    name: "Bioinformatics",
    publisher: "Oxford University Press",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3300,
    impactFactor: 5.8,
    indexing: ["PubMed", "Scopus", "Web of Science", "DBLP"],
    reviewTimeWeeks: "6-10",
    publicationTimeWeeks: "10-14",
    latexTemplateUrl: "https://academic.oup.com/bioinformatics/pages/General_Instructions",
    homeUrl: "https://academic.oup.com/bioinformatics",
    domains: ["Biology", "Bioinformatics", "Computer Science"],
    sjrScore: 2.5,
    keywords: ["sequence analysis", "gene expression", "phylogenetics", "structural bioinformatics", "databases", "algorithms"],
    scopeText: "The leading journal for computational methods, software tools, and database developments in genetics, genomics, and molecular biology.",
    minRecommendedScore: 75,
    methodologyFocus: ["computational", "software", "algorithmic"]
  },
  {
    name: "PLOS Biology",
    publisher: "PLOS",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 4000,
    impactFactor: 9.8,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-8",
    publicationTimeWeeks: "10-14",
    latexTemplateUrl: "https://journals.plos.org/plosbiology/s/submission-guidelines",
    homeUrl: "https://journals.plos.org/plosbiology/",
    domains: ["Biology", "Life Sciences"],
    sjrScore: 3.9,
    keywords: ["ecology", "evolution", "neuroscience", "microbiology", "physiology", "developmental biology"],
    scopeText: "Presents biological research across the whole spectrum of life sciences, emphasizing open data access and biological importance.",
    minRecommendedScore: 78,
    methodologyFocus: ["experimental", "observational"]
  },
  {
    name: "Nature Genetics",
    publisher: "Nature Portfolio",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 11000,
    impactFactor: 31.7,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-10",
    publicationTimeWeeks: "12-18",
    latexTemplateUrl: "https://www.nature.com/ng/authors",
    homeUrl: "https://www.nature.com/ng/",
    domains: ["Biology", "Genomics", "Life Sciences"],
    sjrScore: 12.8,
    keywords: ["human genetics", "disease association", "gwas", "functional genomics", "population genetics"],
    scopeText: "Publishes high-impact research in genetics, genomics, and human hereditary disorders, including genome-wide association studies.",
    minRecommendedScore: 88,
    methodologyFocus: ["experimental", "quantitative", "statistical"]
  },
  {
    name: "Journal of Molecular Biology",
    publisher: "Elsevier",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3850,
    impactFactor: 4.8,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-8",
    publicationTimeWeeks: "8-12",
    latexTemplateUrl: "https://www.elsevier.com/journals/journal-of-molecular-biology/0022-2836/guide-for-authors",
    homeUrl: "https://www.sciencedirect.com/journal/journal-of-molecular-biology",
    domains: ["Biology", "Molecular Biology", "Biochemistry"],
    sjrScore: 1.9,
    keywords: ["macromolecular structure", "protein folding", "biophysics", "structural biology", "macromolecular complexes"],
    scopeText: "Focuses on providing a high-resolution molecular explanation for biological structures and mechanisms.",
    minRecommendedScore: 72,
    methodologyFocus: ["experimental", "structural", "biophysical"]
  },
  {
    name: "eLife",
    publisher: "eLife Sciences Publications",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 2000,
    impactFactor: 7.7,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-10",
    publicationTimeWeeks: "8-12",
    latexTemplateUrl: "https://reviewer.elifesciences.org/author-guide",
    homeUrl: "https://elifesciences.org/",
    domains: ["Biology", "Life Sciences", "Medicine"],
    sjrScore: 3.5,
    keywords: ["evolutionary biology", "neuroscience", "cell biology", "biophysics", "developmental biology"],
    scopeText: "An open-access journal covering biology and biomedicine, using a unique public review process with detailed editor assessments.",
    minRecommendedScore: 76,
    methodologyFocus: ["experimental", "multidisciplinary"]
  },

  // --- Physics / Chemistry / Materials ---
  {
    name: "Physical Review Letters",
    publisher: "American Physical Society",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2900,
    impactFactor: 8.6,
    indexing: ["Scopus", "Web of Science"],
    reviewTimeWeeks: "4-6",
    publicationTimeWeeks: "6-10",
    latexTemplateUrl: "https://journals.aps.org/prl/authors",
    homeUrl: "https://journals.aps.org/prl/",
    domains: ["Physics", "General Science"],
    sjrScore: 3.8,
    keywords: ["quantum mechanics", "condensed matter", "astrophysics", "elementary particles", "statistical physics"],
    scopeText: "The premier international journal for short letters describing fundamental breakthroughs in all areas of physical sciences.",
    minRecommendedScore: 82,
    methodologyFocus: ["theoretical", "experimental"]
  },
  {
    name: "Journal of the American Chemical Society",
    publisher: "American Chemical Society",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 4000,
    impactFactor: 15.0,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "4-6",
    publicationTimeWeeks: "6-10",
    latexTemplateUrl: "https://publish.acs.org/publish/author_guidelines?coden=jacsub",
    homeUrl: "https://pubs.acs.org/journal/jacsub",
    domains: ["Chemistry", "General Science"],
    sjrScore: 5.2,
    keywords: ["organic chemistry", "inorganic chemistry", "biochemistry", "materials chemistry", "catalysis", "spectroscopy"],
    scopeText: "Publishes top-tier research across the entire field of chemistry, including synthesis, materials, and biochemical mechanisms.",
    minRecommendedScore: 85,
    methodologyFocus: ["experimental", "synthesis", "characterization"]
  },
  {
    name: "Angewandte Chemie International Edition",
    publisher: "Wiley-VCH",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 4500,
    impactFactor: 16.6,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "4-6",
    publicationTimeWeeks: "6-10",
    latexTemplateUrl: "https://onlinelibrary.wiley.com/page/journal/15213773/homepage/author-guidelines",
    homeUrl: "https://onlinelibrary.wiley.com/journal/15213773",
    domains: ["Chemistry", "Materials Science"],
    sjrScore: 5.1,
    keywords: ["supramolecular chemistry", "catalysis", "materials science", "nanotechnology", "medicinal chemistry"],
    scopeText: "One of the prime chemistry journals in the world, publishing reviews, communications, and research articles.",
    minRecommendedScore: 84,
    methodologyFocus: ["experimental", "synthesis", "applied"]
  },
  {
    name: "Advanced Materials",
    publisher: "Wiley-VCH",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 5000,
    impactFactor: 29.4,
    indexing: ["Scopus", "Web of Science"],
    reviewTimeWeeks: "6-8",
    publicationTimeWeeks: "8-12",
    latexTemplateUrl: "https://onlinelibrary.wiley.com/page/journal/15214095/homepage/author-guidelines",
    homeUrl: "https://onlinelibrary.wiley.com/journal/15214095",
    domains: ["Materials Science", "Physics", "Chemistry"],
    sjrScore: 8.2,
    keywords: ["nanomaterials", "energy materials", "semiconductors", "biomaterials", "polymers", "thin films"],
    scopeText: "Covers high-impact research in functional materials, nanotechnology, energy storage, and structural engineering.",
    minRecommendedScore: 88,
    methodologyFocus: ["experimental", "characterization", "applied"]
  },
  {
    name: "Nature Materials",
    publisher: "Nature Portfolio",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 11000,
    impactFactor: 41.2,
    indexing: ["Scopus", "Web of Science"],
    reviewTimeWeeks: "6-10",
    publicationTimeWeeks: "12-20",
    latexTemplateUrl: "https://www.nature.com/nmat/authors",
    homeUrl: "https://www.nature.com/nmat/",
    domains: ["Materials Science", "Physics", "Chemistry"],
    sjrScore: 14.5,
    keywords: ["solid-state physics", "materials engineering", "superconductivity", "structural materials", "soft matter"],
    scopeText: "Presents high-impact research in all areas of materials science, focusing on mechanical, electrical, and optical material properties.",
    minRecommendedScore: 92,
    methodologyFocus: ["experimental", "theoretical", "characterization"]
  },
  {
    name: "Nature Physics",
    publisher: "Nature Portfolio",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 11000,
    impactFactor: 19.6,
    indexing: ["Scopus", "Web of Science"],
    reviewTimeWeeks: "6-8",
    publicationTimeWeeks: "12-18",
    latexTemplateUrl: "https://www.nature.com/nphys/authors",
    homeUrl: "https://www.nature.com/nphys/",
    domains: ["Physics"],
    sjrScore: 8.8,
    keywords: ["quantum computation", "astrophysics", "thermodynamics", "condensed matter physics", "optics"],
    scopeText: "Publishes top research across all aspects of physics, both pure and applied, including quantum and relativity theories.",
    minRecommendedScore: 92,
    methodologyFocus: ["theoretical", "experimental"]
  },
  {
    name: "Nature Chemistry",
    publisher: "Nature Portfolio",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 11000,
    impactFactor: 20.8,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-8",
    publicationTimeWeeks: "12-18",
    latexTemplateUrl: "https://www.nature.com/nchem/authors",
    homeUrl: "https://www.nature.com/nchem/",
    domains: ["Chemistry"],
    sjrScore: 7.9,
    keywords: ["synthetic chemistry", "chemical biology", "catalyst design", "computational chemistry", "materials science"],
    scopeText: "Publishes high-impact chemistry research, from physical chemistry and organometallics to chemical biology and green chemistry.",
    minRecommendedScore: 92,
    methodologyFocus: ["experimental", "theoretical", "synthesis"]
  },
  {
    name: "Chemical Science",
    publisher: "Royal Society of Chemistry",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 0,
    impactFactor: 8.4,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "5-7",
    publicationTimeWeeks: "8-12",
    latexTemplateUrl: "https://www.rsc.org/journals-books-databases/journal-authors-reviewers/author-templates/",
    homeUrl: "https://www.rsc.org/journals-books-databases/about-journals/chemical-science/",
    domains: ["Chemistry"],
    sjrScore: 2.8,
    keywords: ["chemical biology", "computational chemistry", "materials science", "sustainable chemistry", "catalysis"],
    scopeText: "The flagship open-access journal of the Royal Society of Chemistry, publishing high-quality findings across the chemical sciences.",
    minRecommendedScore: 78,
    methodologyFocus: ["experimental", "theoretical", "synthesis"]
  },
  {
    name: "Journal of Chemical Physics",
    publisher: "AIP Publishing",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3500,
    impactFactor: 4.4,
    indexing: ["Scopus", "Web of Science"],
    reviewTimeWeeks: "4-6",
    publicationTimeWeeks: "6-10",
    latexTemplateUrl: "https://publishing.aip.org/resources/researchers/templates-and-guidelines/",
    homeUrl: "https://aip.scitation.org/journal/jcp",
    domains: ["Physics", "Chemistry"],
    sjrScore: 1.3,
    keywords: ["spectroscopy", "statistical mechanics", "molecular dynamics", "quantum chemistry", "chemical kinetics"],
    scopeText: "Focuses on the physical principles underlying chemistry, including spectroscopy, thermodynamics, and molecular mechanics.",
    minRecommendedScore: 70,
    methodologyFocus: ["theoretical", "computational", "experimental"]
  },

  // --- Multidisciplinary / General Science ---
  {
    name: "Nature",
    publisher: "Nature Portfolio",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 11000,
    impactFactor: 64.8,
    indexing: ["Scopus", "Web of Science", "PubMed"],
    reviewTimeWeeks: "4-12",
    publicationTimeWeeks: "12-24",
    latexTemplateUrl: "https://www.nature.com/nature/for-authors/formatting-guide",
    homeUrl: "https://www.nature.com/",
    domains: ["Multidisciplinary", "Science", "Biology", "Physics", "Chemistry", "Medicine"],
    sjrScore: 16.5,
    keywords: ["multidisciplinary", "science", "biology", "physics", "climate change", "breakthrough"],
    scopeText: "One of the world's premier weekly multidisciplinary science journals, publishing highly significant original research across all fields.",
    minRecommendedScore: 92,
    methodologyFocus: ["experimental", "theoretical", "quantitative"]
  },
  {
    name: "Science",
    publisher: "AAAS",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 4500,
    impactFactor: 56.9,
    indexing: ["Scopus", "Web of Science", "PubMed"],
    reviewTimeWeeks: "4-8",
    publicationTimeWeeks: "10-20",
    latexTemplateUrl: "https://www.science.org/content/page/instructions-preparing-manuscript",
    homeUrl: "https://www.science.org/",
    domains: ["Multidisciplinary", "Science", "Biology", "Chemistry", "Physics"],
    sjrScore: 14.2,
    keywords: ["multidisciplinary", "science", "genetics", "climate", "archaeology", "paleontology"],
    scopeText: "Publishes peer-reviewed scientific advancements, research reports, and commentary across all scientific fields.",
    minRecommendedScore: 92,
    methodologyFocus: ["experimental", "theoretical", "observational"]
  },
  {
    name: "Proceedings of the National Academy of Sciences",
    publisher: "National Academy of Sciences",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2500,
    impactFactor: 11.1,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "4-6",
    publicationTimeWeeks: "6-10",
    latexTemplateUrl: "https://www.pnas.org/author-center/submitting-your-manuscript",
    homeUrl: "https://www.pnas.org/",
    domains: ["Multidisciplinary", "Science"],
    sjrScore: 4.9,
    keywords: ["biological sciences", "physical sciences", "social sciences", "mathematics", "environmental sciences"],
    scopeText: "One of the world's most-cited multidisciplinary scientific journals, publishing research reports, reviews, and academy proceedings.",
    minRecommendedScore: 84,
    methodologyFocus: ["experimental", "quantitative", "theoretical"]
  },
  {
    name: "Nature Communications",
    publisher: "Nature Portfolio",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 6790,
    impactFactor: 16.6,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-8",
    publicationTimeWeeks: "8-12",
    latexTemplateUrl: "https://www.nature.com/ncomms/authors",
    homeUrl: "https://www.nature.com/ncomms/",
    domains: ["Multidisciplinary", "Science", "Biology", "Chemistry", "Physics", "Earth Science"],
    sjrScore: 5.8,
    keywords: ["biology", "physics", "chemistry", "earth sciences", "engineering", "materials science"],
    scopeText: "An open-access journal publishing high-quality research from all areas of the natural sciences.",
    minRecommendedScore: 80,
    methodologyFocus: ["experimental", "theoretical", "quantitative"]
  },
  {
    name: "Science Advances",
    publisher: "AAAS",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 4500,
    impactFactor: 13.6,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-8",
    publicationTimeWeeks: "10-14",
    latexTemplateUrl: "https://www.science.org/content/page/science-advances-information-authors",
    homeUrl: "https://www.science.org/journal/sciadv",
    domains: ["Multidisciplinary", "Science"],
    sjrScore: 4.6,
    keywords: ["multidisciplinary", "genetics", "nanotechnology", "ecology", "materials", "robotics"],
    scopeText: "The digital-only, open-access extension of Science, covering all branches of science, engineering, and medicine.",
    minRecommendedScore: 78,
    methodologyFocus: ["experimental", "observational", "theoretical"]
  },
  {
    name: "Scientific Reports",
    publisher: "Nature Portfolio",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 2490,
    impactFactor: 4.6,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "6-8",
    publicationTimeWeeks: "8-10",
    latexTemplateUrl: "https://www.nature.com/srep/author-instructions",
    homeUrl: "https://www.nature.com/srep/",
    domains: ["Multidisciplinary", "Science", "Engineering"],
    sjrScore: 1.0,
    keywords: ["applied physics", "clinical medicine", "materials science", "molecular biology", "psychology"],
    scopeText: "An open access journal publishing original research from all areas of the natural and clinical sciences, focused on methodological validity.",
    minRecommendedScore: 55,
    methodologyFocus: ["experimental", "applied", "reproducible-science"]
  },
  {
    name: "PLOS ONE",
    publisher: "PLOS",
    quartile: "Q1",
    accessType: "Open Access",
    apc: 2100,
    impactFactor: 3.7,
    indexing: ["PubMed", "Scopus", "Web of Science"],
    reviewTimeWeeks: "5-8",
    publicationTimeWeeks: "8-12",
    latexTemplateUrl: "https://journals.plos.org/plosone/s/submission-guidelines",
    homeUrl: "https://journals.plos.org/plosone/",
    domains: ["Multidisciplinary", "Science"],
    sjrScore: 0.8,
    keywords: ["biology", "medicine", "social sciences", "physics", "chemistry", "computer science"],
    scopeText: "Accepts research in over 200 subject areas, evaluating papers strictly on technical and methodological rigor rather than novelty.",
    minRecommendedScore: 50,
    methodologyFocus: ["experimental", "reproducible-science", "descriptive"]
  },

  // --- Engineering / Robotics / Signal Processing ---
  {
    name: "IEEE Transactions on Robotics",
    publisher: "IEEE",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2150,
    impactFactor: 7.7,
    indexing: ["Scopus", "IEEE Xplore", "Web of Science"],
    reviewTimeWeeks: "10-14",
    publicationTimeWeeks: "16-24",
    latexTemplateUrl: "https://template-selector.ieee.org/",
    homeUrl: "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8860",
    domains: ["Engineering", "Robotics", "Automation"],
    sjrScore: 3.1,
    keywords: ["robotics", "automation", "sensors", "kinematics", "computer vision", "control algorithms"],
    scopeText: "Focuses on the theory, design, and analysis of robot kinematics, dynamics, control, and sensory-motor systems.",
    minRecommendedScore: 80,
    methodologyFocus: ["experimental", "algorithmic", "theoretical"]
  },
  {
    name: "International Journal of Robotics Research",
    publisher: "SAGE Publishing",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3200,
    impactFactor: 9.2,
    indexing: ["Scopus", "Web of Science"],
    reviewTimeWeeks: "12-16",
    publicationTimeWeeks: "16-24",
    latexTemplateUrl: "https://journals.sagepub.com/author-instructions/IJR",
    homeUrl: "https://journals.sagepub.com/home/ijr",
    domains: ["Engineering", "Robotics"],
    sjrScore: 4.2,
    keywords: ["robotics", "navigation", "legged robots", "manipulation", "planning algorithms", "sensor fusion"],
    scopeText: "The first scholarly journal in robotics, publishing cutting-edge papers on algorithmic and hardware implementations.",
    minRecommendedScore: 85,
    methodologyFocus: ["experimental", "theoretical", "applied"]
  },
  {
    name: "IEEE Transactions on Signal Processing",
    publisher: "IEEE",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2150,
    impactFactor: 5.4,
    indexing: ["Scopus", "IEEE Xplore", "Web of Science"],
    reviewTimeWeeks: "8-12",
    publicationTimeWeeks: "14-20",
    latexTemplateUrl: "https://template-selector.ieee.org/",
    homeUrl: "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=78",
    domains: ["Engineering", "Signal Processing", "Electrical Engineering"],
    sjrScore: 2.1,
    keywords: ["signal processing", "statistical estimation", "filter design", "sensor arrays", "spectral analysis", "wavelets"],
    scopeText: "Covers novel mathematical theories, algorithms, and applications of digital signal and data processing.",
    minRecommendedScore: 78,
    methodologyFocus: ["theoretical", "algorithmic", "experimental"]
  },
  {
    name: "IEEE/ASME Transactions on Mechatronics",
    publisher: "IEEE",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2150,
    impactFactor: 6.4,
    indexing: ["Scopus", "IEEE Xplore", "Web of Science"],
    reviewTimeWeeks: "8-12",
    publicationTimeWeeks: "12-18",
    latexTemplateUrl: "https://template-selector.ieee.org/",
    homeUrl: "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=3516",
    domains: ["Engineering", "Mechatronics", "Mechanical Engineering"],
    sjrScore: 1.9,
    keywords: ["mechatronics", "control systems", "actuators", "sensors", "micro-electromechanical systems", "automotive engineering"],
    scopeText: "Presents synergy in mechatronic designs combining mechanical, electrical, and control system components.",
    minRecommendedScore: 76,
    methodologyFocus: ["applied", "experimental", "applied-engineering"]
  },
  {
    name: "Automatica",
    publisher: "Elsevier",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3300,
    impactFactor: 6.2,
    indexing: ["Scopus", "Web of Science"],
    reviewTimeWeeks: "10-14",
    publicationTimeWeeks: "14-20",
    latexTemplateUrl: "https://www.elsevier.com/journals/automatica/0005-1098/guide-for-authors",
    homeUrl: "https://www.sciencedirect.com/journal/automatica",
    domains: ["Engineering", "Control Theory", "Automation"],
    sjrScore: 3.4,
    keywords: ["control theory", "linear systems", "nonlinear control", "state estimation", "adaptive control", "systems theory"],
    scopeText: "Publishes papers on control theory and applications, covering system modeling, simulation, and feedback design.",
    minRecommendedScore: 82,
    methodologyFocus: ["theoretical", "applied"]
  },
  {
    name: "Signal Processing",
    publisher: "Elsevier",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2900,
    impactFactor: 4.4,
    indexing: ["Scopus", "Web of Science"],
    reviewTimeWeeks: "8-10",
    publicationTimeWeeks: "10-14",
    latexTemplateUrl: "https://www.elsevier.com/journals/signal-processing/0165-1684/guide-for-authors",
    homeUrl: "https://www.sciencedirect.com/journal/signal-processing",
    domains: ["Engineering", "Signal Processing"],
    sjrScore: 1.4,
    keywords: ["signal analysis", "image processing", "radar signal processing", "audio processing", "compressive sensing"],
    scopeText: "Focuses on signal processing algorithms, hardware structures, and systems designed for communication and diagnostics.",
    minRecommendedScore: 70,
    methodologyFocus: ["experimental", "applied", "theoretical"]
  },
  {
    name: "Robotics and Computer-Integrated Manufacturing",
    publisher: "Elsevier",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 3450,
    impactFactor: 10.4,
    indexing: ["Scopus", "Web of Science"],
    reviewTimeWeeks: "8-12",
    publicationTimeWeeks: "12-16",
    latexTemplateUrl: "https://www.elsevier.com/journals/robotics-and-computer-integrated-manufacturing/0736-5845/guide-for-authors",
    homeUrl: "https://www.sciencedirect.com/journal/robotics-and-computer-integrated-manufacturing",
    domains: ["Engineering", "Robotics", "Manufacturing"],
    sjrScore: 2.7,
    keywords: ["flexible manufacturing", "industrial robots", "machining", "cad/cam", "assembly automation"],
    scopeText: "Focuses on user-oriented research in robotics and computer-integrated systems applied to manufacturing.",
    minRecommendedScore: 75,
    methodologyFocus: ["applied", "experimental"]
  },
  {
    name: "IEEE Transactions on Control Systems Technology",
    publisher: "IEEE",
    quartile: "Q1",
    accessType: "Hybrid",
    apc: 2150,
    impactFactor: 4.9,
    indexing: ["Scopus", "IEEE Xplore", "Web of Science"],
    reviewTimeWeeks: "8-12",
    publicationTimeWeeks: "12-18",
    latexTemplateUrl: "https://template-selector.ieee.org/",
    homeUrl: "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=87",
    domains: ["Engineering", "Control Systems", "Applied Control"],
    sjrScore: 1.8,
    keywords: ["industrial control", "aerospace control", "process control", "robotics control", "sensors and actuators"],
    scopeText: "Focuses on the application of control theory to engineering systems, emphasizing industrial relevance and engineering detail.",
    minRecommendedScore: 72,
    methodologyFocus: ["applied", "experimental"]
  }
];
