// AUTO-GENERATED publisher -> logo map. Real brand PNGs where available,
// otherwise a generated monogram SVG so every template shows an accurate,
// consistent, offline-safe logo in the gallery.
export const PUBLISHER_LOGO: Record<string, string> = {
  "AAAI": "/assets/logos/pub-aaai.svg",
  "AAAS": "/assets/logos/science.png",
  "AAS": "/assets/logos/pub-aas.svg",
  "ACL": "/assets/logos/pub-acl.svg",
  "ACM": "/assets/logos/acm.png",
  "ACS": "/assets/logos/pub-acs.svg",
  "AIP": "/assets/logos/pub-aip.svg",
  "AISTATS": "/assets/logos/pub-aistats.svg",
  "AMS": "/assets/logos/pub-ams.svg",
  "APS": "/assets/logos/pub-aps.svg",
  "COLT": "/assets/logos/pub-colt.svg",
  "Caltech": "/assets/logos/pub-caltech.svg",
  "Cambridge": "/assets/logos/pub-cambridge.svg",
  "Chicago": "/assets/logos/pub-chicago.svg",
  "Columbia": "/assets/logos/pub-columbia.svg",
  "Community": "/assets/logos/pub-community.svg",
  "Cornell": "/assets/logos/pub-cornell.svg",
  "DU": "/assets/logos/pub-du.svg",
  "ECAI": "/assets/logos/pub-ecai.svg",
  "EDP Sciences": "/assets/logos/pub-edp-sciences.svg",
  "Elsevier": "/assets/logos/elsevier.png",
  "Generic": "/assets/logos/pub-generic.svg",
  "Georgia Tech": "/assets/logos/pub-georgia-tech.svg",
  "Harvard": "/assets/logos/pub-harvard.svg",
  "ICML": "/assets/logos/pub-icml.svg",
  "IEEE": "/assets/logos/ieee.png",
  "IEEE/CVF": "/assets/logos/ieee.png",
  "IISc Bangalore": "/assets/logos/pub-iisc-bangalore.svg",
  "IIT Bombay": "/assets/logos/pub-iit-bombay.svg",
  "IIT Delhi": "/assets/logos/pub-iit-delhi.svg",
  "IITs": "/assets/logos/pub-iits.svg",
  "IJCAI": "/assets/logos/pub-ijcai.svg",
  "IMS": "/assets/logos/pub-ims.svg",
  "INFORMS": "/assets/logos/pub-informs.svg",
  "IOP": "/assets/logos/pub-iop.svg",
  "JMLR": "/assets/logos/pub-jmlr.svg",
  "JNU": "/assets/logos/pub-jnu.svg",
  "MDPI": "/assets/logos/pub-mdpi.svg",
  "MIT": "/assets/logos/pub-mit.svg",
  "NAS": "/assets/logos/science.png",
  "NYU": "/assets/logos/pub-nyu.svg",
  "Nature Portfolio": "/assets/logos/nature.png",
  "NeurIPS": "/assets/logos/pub-neurips.svg",
  "Oxford": "/assets/logos/pub-oxford.svg",
  "PLOS": "/assets/logos/pub-plos.svg",
  "Princeton": "/assets/logos/pub-princeton.svg",
  "Purdue": "/assets/logos/pub-purdue.svg",
  "RSC": "/assets/logos/pub-rsc.svg",
  "SIAM": "/assets/logos/pub-siam.svg",
  "Springer": "/assets/logos/springer.png",
  "Stanford": "/assets/logos/pub-stanford.svg",
  "Taylor & Francis": "/assets/logos/pub-taylor-francis.svg",
  "Texas A&M": "/assets/logos/pub-texas-a-m.svg",
  "U. Chicago": "/assets/logos/pub-u-chicago.svg",
  "U. Michigan": "/assets/logos/pub-u-michigan.svg",
  "UC Berkeley": "/assets/logos/pub-uc-berkeley.svg",
  "UIUC": "/assets/logos/pub-uiuc.svg",
  "UPenn": "/assets/logos/pub-upenn.svg",
  "UT Austin": "/assets/logos/pub-ut-austin.svg",
  "UW": "/assets/logos/pub-uw.svg",
  "UW Madison": "/assets/logos/pub-uw-madison.svg",
  "Wiley": "/assets/logos/pub-wiley.svg",
  "Yale": "/assets/logos/pub-yale.svg",
};

export function getTemplateLogo(publisher?: string, fallback?: string): string {
  if (publisher && PUBLISHER_LOGO[publisher]) return PUBLISHER_LOGO[publisher];
  return fallback || '';
}
