
export interface TemplateMapping {
  // Existing
  abstractEnv?: string;
  keywordsCmd?: string;
  authorStyle?: 'standard' | 'acm' | 'ieee' | 'elsevier' | 'nature' | 'science';
  sectionPrefix?: boolean;
  sectionStyle?: 'starred' | 'numbered';

  // Citation & Bibliography
  citationStyle?: 'numeric' | 'authoryear' | 'superscript';
  bibliographyStyle?: string;         // e.g. 'IEEEtran', 'apalike', 'acm'
  bibEnv?: 'thebibliography' | 'bibtex';

  // Layout
  columnLayout?: 'single' | 'double';
  floatPlacement?: string;            // e.g. '[h]', '[t]', '[!ht]'

  // Math & Algorithms
  algorithmPackage?: 'algorithm2e' | 'algorithmic' | 'algorithmicx';
  equationNumbering?: 'numbered' | 'unnumbered';

  // Supplementary preamble commands
  preambleExtras?: string[];
}

export interface TemplateMetadata {
  id: string;
  label: string;
  icon: string;
  category: 'Journal' | 'Conference' | 'Basic' | 'Thesis' | 'Presentation' | 'Book' | 'CV';
  subCategory?: string;
  desc: string;
  publisher?: string;
  isCustom?: boolean;
  assetFolder?: string;
  fileExtensions?: string[];
  mapping?: TemplateMapping;
}

export const TEMPLATE_REGISTRY: TemplateMetadata[] = [
  { 
    id: 'blank', 
    label: 'Blank Document', 
    icon: '📄', 
    category: 'Basic', 
    desc: 'Minimal article structure',
    publisher: 'Generic'
  , fileExtensions: [".tex"] },
  
  // --- 1. MULTIDISCIPLINARY & GENERAL SCIENCE ---
  { id: 'nature', label: 'Nature', icon: '/assets/logos/nature.png', category: 'Journal', subCategory: 'Multidisciplinary', desc: 'World\'s leading multidisciplinary science journal.', publisher: 'Nature Portfolio', assetFolder: 'nature', fileExtensions: [".tex",".cls",".sty",".bst",".bib"], mapping: { authorStyle: 'nature', abstractEnv: 'abstract', sectionStyle: 'starred', citationStyle: 'superscript', bibliographyStyle: 'naturemag', columnLayout: 'single' } },
  { id: 'science', label: 'Science', icon: '/assets/logos/science.png', category: 'Journal', subCategory: 'Multidisciplinary', desc: 'Global weekly of the AAAS.', publisher: 'AAAS', assetFolder: 'aaas', fileExtensions: [".tex",".bib",".bst",".cls",".sty"], mapping: { authorStyle: 'science', abstractEnv: 'abstract', sectionStyle: 'starred', citationStyle: 'superscript', columnLayout: 'single' } },
  { id: 'pnas', label: 'PNAS', icon: '/assets/logos/science.png', category: 'Journal', subCategory: 'Multidisciplinary', desc: 'Proceedings of the National Academy of Sciences.', publisher: 'NAS', assetFolder: 'pnas', fileExtensions: [".tex",".bst",".cls",".sty",".bib"], mapping: { authorStyle: 'nature', sectionStyle: 'starred', citationStyle: 'numeric', columnLayout: 'single' } },
  { id: 'nature_comms', label: 'Nature Communications', icon: '/assets/logos/nature.png', category: 'Journal', subCategory: 'Multidisciplinary', desc: 'High-quality open access research.', publisher: 'Nature Portfolio', assetFolder: 'nature', fileExtensions: [".tex",".cls",".sty",".bst",".bib"], mapping: { authorStyle: 'nature', sectionStyle: 'starred', citationStyle: 'superscript', columnLayout: 'single' } },
  { id: 'science_adv', label: 'Science Advances', icon: '/assets/logos/science.png', category: 'Journal', subCategory: 'Multidisciplinary', desc: 'Open access journal of the AAAS.', publisher: 'AAAS', assetFolder: 'aaas', fileExtensions: [".tex",".bib",".bst",".cls",".sty"], mapping: { authorStyle: 'science', sectionStyle: 'starred', citationStyle: 'superscript', columnLayout: 'single' } },
  { id: 'scirep', label: 'Scientific Reports', icon: '/assets/logos/nature.png', category: 'Journal', subCategory: 'Multidisciplinary', desc: 'Open access from the Nature portfolio.', publisher: 'Nature Portfolio', assetFolder: 'scirep', fileExtensions: [".sty",".tex",".bst",".bib",".cls"], mapping: { authorStyle: 'nature', keywordsCmd: 'keywords', sectionStyle: 'starred', citationStyle: 'numeric', columnLayout: 'single' } },
  { id: 'plos_one', label: 'PLOS ONE', icon: '🧬', category: 'Journal', subCategory: 'Multidisciplinary', desc: 'Peer-reviewed open access journal.', publisher: 'PLOS', assetFolder: 'plos', fileExtensions: [".tex",".bst",".cls",".sty",".bib"], mapping: { authorStyle: 'standard', citationStyle: 'numeric', columnLayout: 'single' } },
  { id: 'nature_sust', label: 'Nature Sustainability', icon: '/assets/logos/nature.png', category: 'Journal', subCategory: 'Multidisciplinary', desc: 'Research on sustainability science.', publisher: 'Nature Portfolio', assetFolder: 'nature', fileExtensions: [".tex",".cls",".sty",".bst",".bib"], mapping: { authorStyle: 'nature', sectionStyle: 'starred', citationStyle: 'superscript', columnLayout: 'single' } },

  // --- 2. COMPUTER SCIENCE, AI & IT ---
  { id: 'ieee_tpami', label: 'IEEE TPAMI', icon: '/assets/logos/ieee.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Pattern Analysis and Machine Intelligence.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double', floatPlacement: '[!ht]', algorithmPackage: 'algorithmicx' } },
  { id: 'jmlr', label: 'JMLR', icon: '🤖', category: 'Journal', subCategory: 'AI & CS', desc: 'Journal of Machine Learning Research.', publisher: 'JMLR', assetFolder: 'jmlr', fileExtensions: [".cls",".sty",".bst",".tex",".bib"], mapping: { citationStyle: 'authoryear', columnLayout: 'single' } },
  { id: 'acm_cacm', label: 'CACM', icon: '/assets/logos/acm.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Communications of the ACM.', publisher: 'ACM', assetFolder: 'acm', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'acm', keywordsCmd: 'keywords', citationStyle: 'numeric', bibliographyStyle: 'acm', columnLayout: 'double', algorithmPackage: 'algorithmicx' } },
  { id: 'ieee_tnnls', label: 'IEEE TNNLS', icon: '/assets/logos/ieee.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Neural Networks and Learning Systems.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double', algorithmPackage: 'algorithmicx' } },
  { id: 'acm_tog', label: 'ACM TOG', icon: '/assets/logos/acm.png', category: 'Journal', subCategory: 'AI & CS', desc: 'ACM Transactions on Graphics.', publisher: 'ACM', assetFolder: 'acm', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'acm', citationStyle: 'numeric', bibliographyStyle: 'acm', columnLayout: 'double' } },
  { id: 'elsevier_ai', label: 'Artificial Intelligence', icon: '/assets/logos/elsevier.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Premier AI journal from Elsevier.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'elsevier', keywordsCmd: 'keyword', citationStyle: 'numeric', bibliographyStyle: 'elsarticle-num', columnLayout: 'single', algorithmPackage: 'algorithmicx' } },
  { id: 'elsevier_nn', label: 'Neural Networks', icon: '/assets/logos/elsevier.png', category: 'Journal', subCategory: 'AI & CS', desc: 'The official journal of the INNS.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'elsevier', citationStyle: 'numeric', bibliographyStyle: 'elsarticle-num', columnLayout: 'single' } },
  { id: 'ieee_tkde', label: 'IEEE TKDE', icon: '/assets/logos/ieee.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Knowledge and Data Engineering.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },
  { id: 'ieee_iot', label: 'IEEE Internet of Things', icon: '/assets/logos/ieee.png', category: 'Journal', subCategory: 'AI & CS', desc: 'The IoT Journal of IEEE.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },
  { id: 'acm_toms', label: 'ACM TOMS', icon: '/assets/logos/acm.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Transactions on Mathematical Software.', publisher: 'ACM', assetFolder: 'acm', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'springer_ml', label: 'Machine Learning', icon: '/assets/logos/springer.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Springer Machine Learning journal.', publisher: 'Springer', assetFolder: 'springer', fileExtensions: [".cls",".sty",".tex",".bib",".bst"] },
  { id: 'elsevier_eswa', label: 'Expert Systems', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Expert Systems with Applications.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_nc', label: 'Neurocomputing', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Elsevier Neurocomputing Journal.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_kbs', label: 'Knowledge-Based Systems', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Knowledge-Based Systems journal.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'ieee_tfs', label: 'IEEE Fuzzy Systems', icon: 'https://brand.ieee.org/wp-content/uploads/2021/04/ieee-logo.png', category: 'Journal', subCategory: 'AI & CS', desc: 'Transactions on Fuzzy Systems.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },

  // --- 3. ENGINEERING & ROBOTICS ---
  { id: 'ieee_tac', label: 'IEEE TAC', icon: 'https://brand.ieee.org/wp-content/uploads/2021/04/ieee-logo.png', category: 'Journal', subCategory: 'Engineering', desc: 'Transactions on Automatic Control.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },
  { id: 'ieee_tro', label: 'IEEE Robotics', icon: 'https://brand.ieee.org/wp-content/uploads/2021/04/ieee-logo.png', category: 'Journal', subCategory: 'Engineering', desc: 'Transactions on Robotics.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },
  { id: 'elsevier_auto', label: 'Automatica', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Engineering', desc: 'The journal of IFAC.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'ieee_tsg', label: 'IEEE Smart Grid', icon: 'https://brand.ieee.org/wp-content/uploads/2021/04/ieee-logo.png', category: 'Journal', subCategory: 'Engineering', desc: 'Transactions on Smart Grid.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },
  { id: 'ieee_tsp', label: 'IEEE Signal Proc.', icon: 'https://brand.ieee.org/wp-content/uploads/2021/04/ieee-logo.png', category: 'Journal', subCategory: 'Engineering', desc: 'Transactions on Signal Processing.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },
  { id: 'cambridge_jfm', label: 'Journal Fluid Mech.', icon: 'https://www.cambridge.org/core/themes/cup/img/cup-logo.png', category: 'Journal', subCategory: 'Engineering', desc: 'Cambridge Fluid Mechanics.', publisher: 'Cambridge', assetFolder: 'cambridge', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'ieee_twc', label: 'IEEE Wireless Comm.', icon: 'https://brand.ieee.org/wp-content/uploads/2021/04/ieee-logo.png', category: 'Journal', subCategory: 'Engineering', desc: 'Wireless Communications.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },
  { id: 'ieee_jsac', label: 'IEEE JSAC', icon: 'https://brand.ieee.org/wp-content/uploads/2021/04/ieee-logo.png', category: 'Journal', subCategory: 'Engineering', desc: 'Areas in Communications.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },
  { id: 'wiley_am', label: 'Advanced Materials', icon: 'https://onlinelibrary.wiley.com/favicon.ico', category: 'Journal', subCategory: 'Engineering', desc: 'High impact materials science.', publisher: 'Wiley', assetFolder: 'wiley', fileExtensions: [".tex",".bib",".cls",".sty",".bst"] },
  { id: 'elsevier_ress', label: 'Reliability Eng.', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Engineering', desc: 'System Safety & Reliability.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_asc', label: 'Soft Computing', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Engineering', desc: 'Applied Soft Computing.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'ieee_csm', label: 'IEEE Control Systems', icon: 'https://brand.ieee.org/wp-content/uploads/2021/04/ieee-logo.png', category: 'Journal', subCategory: 'Engineering', desc: 'IEEE Control Systems Magazine.', publisher: 'IEEE', assetFolder: 'ieee', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },
  { id: 'elsevier_jsv', label: 'Sound & Vibration', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Engineering', desc: 'Journal of Sound and Vibration.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_cmame', label: 'Computer Methods', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Engineering', desc: 'Applied Mechanics and Engineering.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },

  // --- 4. PHYSICS & ASTRONOMY ---
  { id: 'aps_prl', label: 'Physical Review Lett.', icon: 'https://journals.aps.org/files/aps-logo.png', category: 'Journal', subCategory: 'Physics', desc: 'Premier physics letters journal.', publisher: 'APS', assetFolder: 'aps', fileExtensions: [".bst",".tex",".cls",".sty",".bib"] },
  { id: 'nature_physics', label: 'Nature Physics', icon: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Nature_Publishing_Group_logo.svg', category: 'Journal', subCategory: 'Physics', desc: 'High-quality physics research.', publisher: 'Nature Portfolio', assetFolder: 'nature', fileExtensions: [".tex",".cls",".sty",".bst",".bib"] },
  { id: 'aps_rmp', label: 'Rev. Modern Physics', icon: 'https://journals.aps.org/files/aps-logo.png', category: 'Journal', subCategory: 'Physics', desc: 'Major physics reviews.', publisher: 'APS', assetFolder: 'aps', fileExtensions: [".bst",".tex",".cls",".sty",".bib"] },
  { id: 'aas_apj', label: 'Astrophysical Journal', icon: 'https://journals.aas.org/wp-content/themes/aas/img/aas-logo.png', category: 'Journal', subCategory: 'Physics', desc: 'The Astrophysical Journal.', publisher: 'AAS', assetFolder: 'aas', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'ras_mnras', label: 'MNRAS', icon: '🏛️', category: 'Journal', subCategory: 'Physics', desc: 'Royal Astronomical Society.', publisher: 'Oxford', assetFolder: 'oxford', fileExtensions: [".tex",".bst",".cls",".sty",".bib"] },
  { id: 'springer_jhep', label: 'JHEP', icon: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Springer_Nature_Logo.svg', category: 'Journal', subCategory: 'Physics', desc: 'High Energy Physics journal.', publisher: 'Springer', assetFolder: 'springer', fileExtensions: [".cls",".sty",".tex",".bib",".bst"] },
  { id: 'aps_pra', label: 'Physical Review A-E', icon: 'https://journals.aps.org/files/aps-logo.png', category: 'Journal', subCategory: 'Physics', desc: 'APS Core Physics Series.', publisher: 'APS', assetFolder: 'aps', fileExtensions: [".bst",".tex",".cls",".sty",".bib"] },
  { id: 'edps_aa', label: 'Astronomy & Astrophys.', icon: '🌌', category: 'Journal', subCategory: 'Physics', desc: 'A&A Journal.', publisher: 'EDP Sciences', assetFolder: 'edp', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_npb', label: 'Nuclear Physics B', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Physics', desc: 'Nuclear and Particle Physics.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_plb', label: 'Physics Letters B', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Physics', desc: 'High energy and nuclear physics.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'aip_apl', label: 'Applied Phys. Lett.', icon: 'https://publishing.aip.org/wp-content/themes/aip-publishing/images/aip-publishing-logo.png', category: 'Journal', subCategory: 'Physics', desc: 'Applied Physics Letters.', publisher: 'AIP', assetFolder: 'aip', fileExtensions: [".cls",".sty",".bst",".tex",".bib"] },
  { id: 'aip_jcp', label: 'Journal Chem. Phys.', icon: 'https://publishing.aip.org/wp-content/themes/aip-publishing/images/aip-publishing-logo.png', category: 'Journal', subCategory: 'Physics', desc: 'Chemical Physics journal.', publisher: 'AIP', assetFolder: 'aip', fileExtensions: [".cls",".sty",".bst",".tex",".bib"] },
  { id: 'iop_jcap', label: 'JCAP', icon: 'https://iopscience.iop.org/img/iop-logo.png', category: 'Journal', subCategory: 'Physics', desc: 'Cosmology and Astroparticle Physics.', publisher: 'IOP', assetFolder: 'iop', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_ppnp', label: 'Particle & Nuclear', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Physics', desc: 'Progress in Physics.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'springer_solar', label: 'Solar Physics', icon: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Springer_Nature_Logo.svg', category: 'Journal', subCategory: 'Physics', desc: 'Springer Solar Physics.', publisher: 'Springer', assetFolder: 'springer', fileExtensions: [".cls",".sty",".tex",".bib",".bst"] },

  // --- 5. MATHEMATICS & STATISTICS ---
  { id: 'princeton_annals', label: 'Annals of Mathematics', icon: '🏛️', category: 'Journal', subCategory: 'Mathematics', desc: 'The most prestigious math journal.', publisher: 'Princeton', assetFolder: 'math', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'jams', label: 'Journal of AMS', icon: 'https://www.ams.org/favicon.ico', category: 'Journal', subCategory: 'Mathematics', desc: 'Official journal of the AMS.', publisher: 'AMS', assetFolder: 'ams', fileExtensions: [".cls",".sty",".bst",".tex",".bib"] },
  { id: 'springer_invent', label: 'Inventiones Math.', icon: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Springer_Nature_Logo.svg', category: 'Journal', subCategory: 'Mathematics', desc: 'Top tier math research.', publisher: 'Springer', assetFolder: 'springer', fileExtensions: [".cls",".sty",".tex",".bib",".bst"] },
  { id: 'siam_review', label: 'SIAM Review', icon: 'https://www.siam.org/images/SIAM-logo-footer.png', category: 'Journal', subCategory: 'Mathematics', desc: 'Major reviews in applied math.', publisher: 'SIAM', assetFolder: 'siam', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'siam_numan', label: 'SIAM Numerical Anal.', icon: 'https://www.siam.org/images/SIAM-logo-footer.png', category: 'Journal', subCategory: 'Mathematics', desc: 'Numerical Analysis Journal.', publisher: 'SIAM', assetFolder: 'siam', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'siam_opt', label: 'SIAM Optimization', icon: 'https://www.siam.org/images/SIAM-logo-footer.png', category: 'Journal', subCategory: 'Mathematics', desc: 'Optimization research.', publisher: 'SIAM', assetFolder: 'siam', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ims_annals_stat', label: 'Annals of Statistics', icon: '📊', category: 'Journal', subCategory: 'Mathematics', desc: 'Top tier statistics journal.', publisher: 'IMS', assetFolder: 'ims', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'jrss', label: 'JRSS (Series B)', icon: '📈', category: 'Journal', subCategory: 'Mathematics', desc: 'Royal Statistical Society.', publisher: 'Wiley', assetFolder: 'wiley', fileExtensions: [".tex",".bib",".cls",".sty",".bst"] },
  { id: 'oxford_biometrika', label: 'Biometrika', icon: '🧬', category: 'Journal', subCategory: 'Mathematics', desc: 'Oxford Biometrika journal.', publisher: 'Oxford', assetFolder: 'oxford', fileExtensions: [".tex",".bst",".cls",".sty",".bib"] },
  { id: 'elsevier_jcp_math', label: 'Computational Phys.', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Mathematics', desc: 'Computational Physics.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'springer_mp', label: 'Math Programming', icon: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Springer_Nature_Logo.svg', category: 'Journal', subCategory: 'Mathematics', desc: 'Mathematical Programming.', publisher: 'Springer', assetFolder: 'springer', fileExtensions: [".cls",".sty",".tex",".bib",".bst"] },
  { id: 'elsevier_jfa', label: 'Functional Analysis', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Mathematics', desc: 'Journal of Functional Analysis.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_dm', label: 'Discrete Mathematics', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Mathematics', desc: 'Discrete Math research.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_jalgebra', label: 'Journal of Algebra', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Mathematics', desc: 'Pure Algebra research.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'cambridge_an', label: 'Acta Numerica', icon: 'https://www.cambridge.org/core/themes/cup/img/cup-logo.png', category: 'Journal', subCategory: 'Mathematics', desc: 'Numerical Analysis Reviews.', publisher: 'Cambridge', assetFolder: 'cambridge', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'siam_sisc', label: 'SIAM Sci. Computing', icon: 'https://www.siam.org/images/SIAM-logo-footer.png', category: 'Journal', subCategory: 'Mathematics', desc: 'Scientific Computing.', publisher: 'SIAM', assetFolder: 'siam', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },

  // --- 6. CHEMISTRY & MATERIALS SCIENCE ---
  { id: 'acs_jacs', label: 'JACS', icon: 'https://pubs.acs.org/pb-assets/images/logos/acs-logo.svg', category: 'Journal', subCategory: 'Chemistry', desc: 'American Chemical Society.', publisher: 'ACS', assetFolder: 'acs', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'wiley_acie', label: 'Angewandte Chemie', icon: 'https://onlinelibrary.wiley.com/favicon.ico', category: 'Journal', subCategory: 'Chemistry', desc: 'International Edition.', publisher: 'Wiley', assetFolder: 'wiley', fileExtensions: [".tex",".bib",".cls",".sty",".bst"] },
  { id: 'rsc_chemsci', label: 'Chemical Science', icon: '🧪', category: 'Journal', subCategory: 'Chemistry', desc: 'Royal Society of Chemistry.', publisher: 'RSC', assetFolder: 'rsc', fileExtensions: [".tex",".bst",".cls",".sty",".bib"] },
  { id: 'nature_chem', label: 'Nature Chemistry', icon: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Nature_Publishing_Group_logo.svg', category: 'Journal', subCategory: 'Chemistry', desc: 'Top tier chemistry.', publisher: 'Nature Portfolio', assetFolder: 'nature', fileExtensions: [".tex",".cls",".sty",".bst",".bib"] },
  { id: 'wiley_afm', label: 'Adv. Functional Mat.', icon: 'https://onlinelibrary.wiley.com/favicon.ico', category: 'Journal', subCategory: 'Chemistry', desc: 'Functional materials.', publisher: 'Wiley', assetFolder: 'wiley', fileExtensions: [".tex",".bib",".cls",".sty",".bst"] },
  { id: 'acs_jpcl', label: 'Phys. Chem. Letters', icon: 'https://pubs.acs.org/pb-assets/images/logos/acs-logo.svg', category: 'Journal', subCategory: 'Chemistry', desc: 'Physical Chemistry.', publisher: 'ACS', assetFolder: 'acs', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'acs_nano', label: 'ACS Nano', icon: 'https://pubs.acs.org/pb-assets/images/logos/acs-logo.svg', category: 'Journal', subCategory: 'Chemistry', desc: 'Nanoscience and nanotechnology.', publisher: 'ACS', assetFolder: 'acs', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'rsc_pccp', label: 'PCCP', icon: '🧪', category: 'Journal', subCategory: 'Chemistry', desc: 'Physical Chemistry Chem. Phys.', publisher: 'RSC', assetFolder: 'rsc', fileExtensions: [".tex",".bst",".cls",".sty",".bib"] },
  { id: 'acs_nano_lett', label: 'Nano Letters', icon: 'https://pubs.acs.org/pb-assets/images/logos/acs-logo.svg', category: 'Journal', subCategory: 'Chemistry', desc: 'Nano research letters.', publisher: 'ACS', assetFolder: 'acs', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'rsc_jmca', label: 'J. Materials Chem. A', icon: '🧪', category: 'Journal', subCategory: 'Chemistry', desc: 'Materials for energy.', publisher: 'RSC', assetFolder: 'rsc', fileExtensions: [".tex",".bst",".cls",".sty",".bib"] },

  // --- 7. ECONOMICS & SOCIAL SCIENCES ---
  { id: 'econometrica', label: 'Econometrica', icon: '📊', category: 'Journal', subCategory: 'Economics', desc: 'The Econometric Society.', publisher: 'Wiley', assetFolder: 'wiley', fileExtensions: [".tex",".bib",".cls",".sty",".bst"] },
  { id: 'oxford_qje', label: 'QJE', icon: '📈', category: 'Journal', subCategory: 'Economics', desc: 'Quarterly Journal of Econ.', publisher: 'Oxford', assetFolder: 'oxford', fileExtensions: [".tex",".bst",".cls",".sty",".bib"] },
  { id: 'chicago_jpe', label: 'Political Economy', icon: '🏛️', category: 'Journal', subCategory: 'Economics', desc: 'Journal of Political Economy.', publisher: 'Chicago', assetFolder: 'chicago', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'oxford_res', label: 'Review Econ. Studies', icon: '📉', category: 'Journal', subCategory: 'Economics', desc: 'REStud.', publisher: 'Oxford', assetFolder: 'oxford', fileExtensions: [".tex",".bst",".cls",".sty",".bib"] },
  { id: 'elsevier_jet', label: 'Economic Theory', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Economics', desc: 'Journal of Economic Theory.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_geb', label: 'Games & Behavior', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Economics', desc: 'Games and Economic Behavior.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'elsevier_jfe', label: 'Financial Econ.', icon: 'https://www.elsevier.com/__data/assets/image/0009/101889/elsevier-logo-white-on-orange.png', category: 'Journal', subCategory: 'Economics', desc: 'Journal of Financial Econ.', publisher: 'Elsevier', assetFolder: 'elsevier', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'informs_ms', label: 'Management Science', icon: '📋', category: 'Journal', subCategory: 'Economics', desc: 'INFORMS Management Science.', publisher: 'INFORMS', assetFolder: 'informs', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'informs_or', label: 'Operations Research', icon: '⚙️', category: 'Journal', subCategory: 'Economics', desc: 'INFORMS Operations Research.', publisher: 'INFORMS', assetFolder: 'informs', fileExtensions: [".bst",".cls",".sty",".tex",".bib"] },
  { id: 'wiley_mf', label: 'Mathematical Finance', icon: '🧮', category: 'Journal', subCategory: 'Economics', desc: 'Wiley Math Finance.', publisher: 'Wiley', assetFolder: 'wiley', fileExtensions: [".tex",".bib",".cls",".sty",".bst"] },

  // --- 8. LIFE SCIENCES, BIOLOGY & MEDICINE ---
  { id: 'nature_biotech', label: 'Nature Biotech', icon: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Nature_Publishing_Group_logo.svg', category: 'Journal', subCategory: 'Life Sciences', desc: 'Biotechnology research.', publisher: 'Nature Portfolio', assetFolder: 'nature', fileExtensions: [".tex",".cls",".sty",".bst",".bib"] },
  { id: 'nature_med', label: 'Nature Medicine', icon: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Nature_Publishing_Group_logo.svg', category: 'Journal', subCategory: 'Life Sciences', desc: 'Biomedical research.', publisher: 'Nature Portfolio', assetFolder: 'nature', fileExtensions: [".tex",".cls",".sty",".bst",".bib"] },
  { id: 'nature_meth', label: 'Nature Methods', icon: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Nature_Publishing_Group_logo.svg', category: 'Journal', subCategory: 'Life Sciences', desc: 'New techniques in life sciences.', publisher: 'Nature Portfolio', assetFolder: 'nature', fileExtensions: [".tex",".cls",".sty",".bst",".bib"] },
  { id: 'oxford_bioinfo', label: 'Bioinformatics', icon: '🧬', category: 'Journal', subCategory: 'Life Sciences', desc: 'Bioinformatics and biology.', publisher: 'Oxford', assetFolder: 'oxford', fileExtensions: [".tex",".bst",".cls",".sty",".bib"] },
  { id: 'plos_comp_bio', label: 'PLOS Comp. Bio.', icon: 'https://journals.plos.org/plosone/static/img/logo.png', category: 'Journal', subCategory: 'Life Sciences', desc: 'Computational biology.', publisher: 'PLOS', assetFolder: 'plos', fileExtensions: [".tex",".bst",".cls",".sty",".bib"] },
  { id: 'springer_bmc', label: 'BMC Bioinformatics', icon: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Springer_Nature_Logo.svg', category: 'Journal', subCategory: 'Life Sciences', desc: 'Open access bioinformatics.', publisher: 'Springer', assetFolder: 'springer', fileExtensions: [".cls",".sty",".tex",".bib",".bst"] },
  { id: 'oxford_nar', label: 'Nucleic Acids Res.', icon: '🧬', category: 'Journal', subCategory: 'Life Sciences', desc: 'Oxford NAR.', publisher: 'Oxford', assetFolder: 'oxford', fileExtensions: [".tex",".bst",".cls",".sty",".bib"] },

  // --- THESIS & UNIVERSITIES ---
  { id: 'thesis_mit', label: 'MIT Dissertation', icon: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/MIT_logo.svg', category: 'Thesis', subCategory: 'Global', desc: 'Official MIT graduate thesis.', publisher: 'MIT', assetFolder: 'thesis', fileExtensions: [".tex",".bst",".bib",".cls",".sty"] },
  { id: 'thesis_stanford', label: 'Stanford Thesis', icon: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Stanford_University_logo.svg', category: 'Thesis', subCategory: 'Global', desc: 'Standard Stanford dissertation.', publisher: 'Stanford', assetFolder: 'thesis', fileExtensions: [".tex",".bst",".bib",".cls",".sty"] },
  { id: 'thesis_oxford', label: 'Oxford OCIAM', icon: '🏛️', category: 'Thesis', subCategory: 'Global', desc: 'Oxford Mathematical Institute.', publisher: 'Oxford', assetFolder: 'thesis', fileExtensions: [".tex",".bst",".bib",".cls",".sty"] },
  { id: 'thesis_cambridge', label: 'Cambridge PhD', icon: '🎓', category: 'Thesis', subCategory: 'Global', desc: 'University of Cambridge PhD.', publisher: 'Cambridge', assetFolder: 'thesis', fileExtensions: [".tex",".bst",".bib",".cls",".sty"] },
  { id: 'thesis_iitd', label: 'IIT Delhi Thesis', icon: '🇮🇳', category: 'Thesis', subCategory: 'India', desc: 'Standard IIT Delhi dissertation.', publisher: 'IIT Delhi', assetFolder: 'thesis', fileExtensions: [".tex",".bst",".bib",".cls",".sty"] },
  { id: 'thesis_iitb', label: 'IIT Bombay Thesis', icon: '🇮🇳', category: 'Thesis', subCategory: 'India', desc: 'Official IIT Bombay format.', publisher: 'IIT Bombay', assetFolder: 'thesis', fileExtensions: [".tex",".bst",".bib",".cls",".sty"] },
  { id: 'thesis_iisc', label: 'IISc PhD Thesis', icon: '🧬', category: 'Thesis', subCategory: 'India', desc: 'IISc Bangalore thesis layout.', publisher: 'IISc Bangalore', assetFolder: 'thesis', fileExtensions: [".tex",".bst",".bib",".cls",".sty"] },
  { id: 'thesis_jnu', label: 'JNU Thesis', icon: '🇮🇳', category: 'Thesis', subCategory: 'India', desc: 'Jawaharlal Nehru University.', publisher: 'JNU', assetFolder: 'thesis', fileExtensions: [".tex",".bst",".bib",".cls",".sty"] },
  { id: 'thesis_du', label: 'Delhi Univ Thesis', icon: '🇮🇳', category: 'Thesis', subCategory: 'India', desc: 'University of Delhi.', publisher: 'DU', assetFolder: 'thesis', fileExtensions: [".tex",".bst",".bib",".cls",".sty"] },

  // --- CV & RESUMES ---
  { id: 'cv_academic_harvard', label: 'Harvard CV', icon: '📋', category: 'CV', subCategory: 'Academic', desc: 'Classic Harvard CV style.', publisher: 'Harvard', assetFolder: 'cv', fileExtensions: [".cls",".sty",".tex",".bst",".bib"] },
  { id: 'cv_yale', label: 'Yale Resume', icon: '💼', category: 'CV', subCategory: 'Professional', desc: 'Yale SOM professional resume.', publisher: 'Yale', assetFolder: 'cv', fileExtensions: [".cls",".sty",".tex",".bst",".bib"] },
  { id: 'cv_iit_placement', label: 'IIT Placement CV', icon: '🇮🇳', category: 'CV', subCategory: 'Professional', desc: 'The 1-page IIT standard.', publisher: 'IITs', assetFolder: 'cv', fileExtensions: [".cls",".sty",".tex",".bst",".bib"] },
  { id: 'cv_overleaf_modern', label: 'Modern CV', icon: '✨', category: 'CV', subCategory: 'Designer', desc: 'Stylish Overleaf template.', publisher: 'Community', assetFolder: 'cv', fileExtensions: [".cls",".sty",".tex",".bst",".bib"] },

  // --- CONFERENCE TEMPLATES ---
  { id: 'conf_ieee', label: 'IEEE Conference', icon: '/assets/logos/ieee.png', category: 'Conference', subCategory: 'Engineering', desc: 'Standard IEEE 2-column conference format.', publisher: 'IEEE', assetFolder: 'ieee_conf', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'ieee', keywordsCmd: 'IEEEkeywords', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double', floatPlacement: '[!ht]', algorithmPackage: 'algorithmicx' } },
  { id: 'conf_acm', label: 'ACM SIGCONF', icon: 'https://www.acm.org/images/acm_logo_tablet.png', category: 'Conference', subCategory: 'CS', desc: 'Standard ACM Proceedings (sigconf).', publisher: 'ACM', assetFolder: 'acm_conf', fileExtensions: [".bst",".cls",".sty",".tex",".bib"], mapping: { authorStyle: 'acm', keywordsCmd: 'keywords', citationStyle: 'numeric', bibliographyStyle: 'acm', columnLayout: 'double', algorithmPackage: 'algorithmicx' } },
  { id: 'conf_neurips', label: 'NeurIPS', icon: '🧠', category: 'Conference', subCategory: 'AI', desc: 'Neural Information Processing Systems format.', publisher: 'NeurIPS', assetFolder: 'neurips', fileExtensions: [".tex",".sty",".bib",".bst"], mapping: { authorStyle: 'nature', citationStyle: 'numeric', columnLayout: 'single', algorithmPackage: 'algorithmicx' } },
  { id: 'conf_icml', label: 'ICML', icon: '🤖', category: 'Conference', subCategory: 'AI', desc: 'International Conference on Machine Learning.', publisher: 'ICML', assetFolder: 'icml', fileExtensions: [".bst",".sty",".tex",".bib"], mapping: { authorStyle: 'nature', citationStyle: 'numeric', columnLayout: 'single', algorithmPackage: 'algorithmicx' } },
  { id: 'conf_cvpr', label: 'CVPR/ICCV', icon: '👁️', category: 'Conference', subCategory: 'Vision', desc: 'Computer Vision and Pattern Recognition.', publisher: 'IEEE/CVF', assetFolder: 'cvpr', fileExtensions: [".sty",".bst",".tex",".bib"], mapping: { authorStyle: 'ieee', citationStyle: 'numeric', bibliographyStyle: 'IEEEtran', columnLayout: 'double' } },
  { id: 'conf_emnlp', label: 'EMNLP/ACL', icon: '🗣️', category: 'Conference', subCategory: 'NLP', desc: 'Computational Linguistics (ACL/EMNLP).', publisher: 'ACL', assetFolder: 'acl', fileExtensions: [".sty",".bst",".tex",".bib"], mapping: { authorStyle: 'nature', citationStyle: 'authoryear', columnLayout: 'single' } },

  // --- PRESENTATION (BEAMER) ---
  { id: 'beamer_metropolis', label: 'Metropolis', icon: '🏙️', category: 'Presentation', subCategory: 'Modern', desc: 'Modern minimalist Beamer theme.', publisher: 'Generic', assetFolder: 'beamer', fileExtensions: [".tex",".bst",".bib"] },
  { id: 'beamer_madrid', label: 'Madrid', icon: '🏛️', category: 'Presentation', subCategory: 'Classic', desc: 'Traditional blue-themed Beamer slides.', publisher: 'Generic', assetFolder: 'beamer', fileExtensions: [".tex",".bst",".bib"] },
  { id: 'beamer_berlin', label: 'Berlin', icon: '🇩🇪', category: 'Presentation', subCategory: 'Academic', desc: 'Professional navigation-heavy theme.', publisher: 'Generic', assetFolder: 'beamer', fileExtensions: [".tex",".bst",".bib"] },
  { id: 'beamer_cambridge', label: 'Cambridge US', icon: '🎓', category: 'Presentation', subCategory: 'Academic', desc: 'Clean academic presentation style.', publisher: 'Generic', assetFolder: 'beamer', fileExtensions: [".tex",".bst",".bib"] },
  { id: 'beamer_focus', label: 'Focus', icon: '🎯', category: 'Presentation', subCategory: 'Minimal', desc: 'High-contrast focused presentation.', publisher: 'Generic', assetFolder: 'beamer', fileExtensions: [".tex",".bst",".bib"] },

  // --- 185+ NEW TEMPLATES (IEEE, Elsevier, Springer, Wiley, Cambridge, Oxford, T&F, MDPI, Conferences, Thesis) ---
  { id: 'ieee_access', label: 'IEEE Access', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'IEEE Access.', publisher: 'IEEE', assetFolder: 'ieee_access', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tcas1', label: 'IEEE TCAS-I', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Circuits and Systems I.', publisher: 'IEEE', assetFolder: 'ieee_tcas1', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tcas2', label: 'IEEE TCAS-II', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Circuits and Systems II.', publisher: 'IEEE', assetFolder: 'ieee_tcas2', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tcomm', label: 'IEEE TCOM', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Communications.', publisher: 'IEEE', assetFolder: 'ieee_tcomm', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tcomml', label: 'IEEE COMML', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Communications Letters.', publisher: 'IEEE', assetFolder: 'ieee_tcomml', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tcs', label: 'IEEE Trans. Computers', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Computing.', publisher: 'IEEE', assetFolder: 'ieee_tcs', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tcyb', label: 'IEEE TCYB', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Cybernetics.', publisher: 'IEEE', assetFolder: 'ieee_tcyb', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_ted', label: 'IEEE TED', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Electron Devices.', publisher: 'IEEE', assetFolder: 'ieee_ted', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tg', label: 'IEEE TG', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Games.', publisher: 'IEEE', assetFolder: 'ieee_tg', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tgrs', label: 'IEEE TGRS', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Remote Sensing.', publisher: 'IEEE', assetFolder: 'ieee_tgrs', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_thi', label: 'IEEE THI', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Human-Machine Systems.', publisher: 'IEEE', assetFolder: 'ieee_thi', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tii', label: 'IEEE TII', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Industrial Informatics.', publisher: 'IEEE', assetFolder: 'ieee_tii', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tim', label: 'IEEE TIM', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Instrumentation and Measurement.', publisher: 'IEEE', assetFolder: 'ieee_tim', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tmc', label: 'IEEE TMC', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Mobile Computing.', publisher: 'IEEE', assetFolder: 'ieee_tmc', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tmm', label: 'IEEE TMM', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Multimedia.', publisher: 'IEEE', assetFolder: 'ieee_tmm', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tns', label: 'IEEE TNS', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Nuclear Science.', publisher: 'IEEE', assetFolder: 'ieee_tns', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_ton', label: 'IEEE TON', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Networking.', publisher: 'IEEE', assetFolder: 'ieee_ton', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tpds', label: 'IEEE TPDS', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Parallel and Distributed Systems.', publisher: 'IEEE', assetFolder: 'ieee_tpds', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'ieee_tsm', label: 'IEEE TSMC', icon: '📄', category: 'Journal', subCategory: 'Engineering', desc: 'Systems, Man, and Cybernetics.', publisher: 'IEEE', assetFolder: 'ieee_tsm', fileExtensions: [".tex",".bib",".bst",".cls",".sty"] },
  { id: 'elsevier_aer', label: 'Applied Energy', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Applied Energy.', publisher: 'Elsevier', assetFolder: 'elsevier_aer', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_aml', label: 'Appl Math Lett', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Applied Mathematics Letters.', publisher: 'Elsevier', assetFolder: 'elsevier_aml', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_amp', label: 'Appl Math Modelling', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Applied Mathematical Modelling.', publisher: 'Elsevier', assetFolder: 'elsevier_amp', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_cce', label: 'Comput Chem Eng', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Computers and Chemical Engineering.', publisher: 'Elsevier', assetFolder: 'elsevier_cce', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_cms', label: 'CMAME', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Computer Methods in Applied Mechanics.', publisher: 'Elsevier', assetFolder: 'elsevier_cms', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_cpl', label: 'Chem Phys Lett', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Chemical Physics Letters.', publisher: 'Elsevier', assetFolder: 'elsevier_cpl', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_energy', label: 'Energy', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Energy.', publisher: 'Elsevier', assetFolder: 'elsevier_energy', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_engstruct', label: 'Eng Struct', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Engineering Structures.', publisher: 'Elsevier', assetFolder: 'elsevier_engstruct', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_eng', label: 'Eng Appl AI', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Engineering Applications of AI.', publisher: 'Elsevier', assetFolder: 'elsevier_eng', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_ijhmt', label: 'IJHMT', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Int. J. Heat and Mass Transfer.', publisher: 'Elsevier', assetFolder: 'elsevier_ijhmt', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_ijpe', label: 'Int J Plasticity', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Int. J. Plasticity.', publisher: 'Elsevier', assetFolder: 'elsevier_ijpe', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_ijss', label: 'IJSS', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Int. J. Solids and Structures.', publisher: 'Elsevier', assetFolder: 'elsevier_ijss', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_japp', label: 'J Appl Physics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Applied Physics.', publisher: 'Elsevier', assetFolder: 'elsevier_japp', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_jca', label: 'JCAM', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Computational and Applied Mathematics.', publisher: 'Elsevier', assetFolder: 'elsevier_jca', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_jfm', label: 'J Fluid Mech', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Fluid Mechanics.', publisher: 'Elsevier', assetFolder: 'elsevier_jfm', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_jma', label: 'JMPS', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Mechanics and Physics of Solids.', publisher: 'Elsevier', assetFolder: 'elsevier_jma', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_jmp', label: 'J Math Physics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Mathematical Physics.', publisher: 'Elsevier', assetFolder: 'elsevier_jmp', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_ny', label: 'Nonlinear Anal', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Nonlinear Analysis.', publisher: 'Elsevier', assetFolder: 'elsevier_ny', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_omega', label: 'Omega', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Omega.', publisher: 'Elsevier', assetFolder: 'elsevier_omega', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_phya', label: 'Physica A', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Physica A.', publisher: 'Elsevier', assetFolder: 'elsevier_phya', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_phyb', label: 'Physica B', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Physica B.', publisher: 'Elsevier', assetFolder: 'elsevier_phyb', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_prel', label: 'Phys Lett A', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Physics Letters A.', publisher: 'Elsevier', assetFolder: 'elsevier_prel', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_rinp', label: 'Results in Physics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Results in Physics.', publisher: 'Elsevier', assetFolder: 'elsevier_rinp', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'elsevier_ssc', label: 'Solid State Comms', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Solid State Communications.', publisher: 'Elsevier', assetFolder: 'elsevier_ssc', fileExtensions: [".tex",".bib",".cls",".sty"] },
  { id: 'springer_aejc', label: 'Adv Electron Com', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Advances in Electronic Commerce.', publisher: 'Springer', assetFolder: 'springer_aejc', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_calc', label: 'Calc Var PDE', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Calculus of Variations.', publisher: 'Springer', assetFolder: 'springer_calc', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_cm', label: 'Comput Mech', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Computational Mechanics.', publisher: 'Springer', assetFolder: 'springer_cm', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_epjc', label: 'Eur Phys J C', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Eur. Phys. J. C.', publisher: 'Springer', assetFolder: 'springer_epjc', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_epjp', label: 'Eur Phys J Plus', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Eur. Phys. J. Plus.', publisher: 'Springer', assetFolder: 'springer_epjp', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_gr', label: 'Gen Rel Grav', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'General Relativity and Gravitation.', publisher: 'Springer', assetFolder: 'springer_gr', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_ijfp', label: 'Int J Fracture', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Int. J. Fracture.', publisher: 'Springer', assetFolder: 'springer_ijfp', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_ijms', label: 'Int J Multiphase', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Int. J. Multiphase Flow.', publisher: 'Springer', assetFolder: 'springer_ijms', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_jace', label: 'J Am Ceram Soc', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Am. Ceramic Society.', publisher: 'Springer', assetFolder: 'springer_jace', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_jano', label: 'J Nanopart Res', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Nanoparticle Research.', publisher: 'Springer', assetFolder: 'springer_jano', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_jcph', label: 'J Comput Physics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Computational Physics.', publisher: 'Springer', assetFolder: 'springer_jcph', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_jms', label: 'J Mater Sci', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Materials Science.', publisher: 'Springer', assetFolder: 'springer_jms', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_nap', label: 'Nanoparticle Res', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Nanoparticle Research.', publisher: 'Springer', assetFolder: 'springer_nap', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'springer_pde', label: 'PDE', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Partial Differential Equations.', publisher: 'Springer', assetFolder: 'springer_pde', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'wiley_bio', label: 'Biometrics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Biometrics.', publisher: 'Wiley', assetFolder: 'wiley_bio', fileExtensions: [".tex",".bib"] },
  { id: 'wiley_borb', label: 'Biometrika', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Biometrika.', publisher: 'Wiley', assetFolder: 'wiley_borb', fileExtensions: [".tex",".bib"] },
  { id: 'wiley_chem', label: 'Chem Eur J', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Chemistry A European Journal.', publisher: 'Wiley', assetFolder: 'wiley_chem', fileExtensions: [".tex",".bib"] },
  { id: 'wiley_cjt', label: 'Can J Stat', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Canadian J. Statistics.', publisher: 'Wiley', assetFolder: 'wiley_cjt', fileExtensions: [".tex",".bib"] },
  { id: 'wiley_em', label: 'Econ Modelling', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Economic Modelling.', publisher: 'Wiley', assetFolder: 'wiley_em', fileExtensions: [".tex",".bib"] },
  { id: 'wiley_ijac', label: 'Int J Algebra', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Int. J. Algebra and Computation.', publisher: 'Wiley', assetFolder: 'wiley_ijac', fileExtensions: [".tex",".bib"] },
  { id: 'wiley_jap', label: 'J Appl Polym Sci', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Applied Polymer Science.', publisher: 'Wiley', assetFolder: 'wiley_jap', fileExtensions: [".tex",".bib"] },
  { id: 'wiley_jcs', label: 'J Cell Science', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Cell Science.', publisher: 'Wiley', assetFolder: 'wiley_jcs', fileExtensions: [".tex",".bib"] },
  { id: 'wiley_nfa', label: 'Nonlinear Anal RWA', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Nonlinear Analysis: Real World.', publisher: 'Wiley', assetFolder: 'wiley_nfa', fileExtensions: [".tex",".bib"] },
  { id: 'wiley_rma', label: 'Risk Mgmt', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Risk Management.', publisher: 'Wiley', assetFolder: 'wiley_rma', fileExtensions: [".tex",".bib"] },
  { id: 'cambridge_aja', label: 'Astronomical J', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Astronomical Journal.', publisher: 'Cambridge', assetFolder: 'cambridge_aja', fileExtensions: [".tex",".bib"] },
  { id: 'cambridge_ajp', label: 'Am J Physics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'American J. Physics.', publisher: 'Cambridge', assetFolder: 'cambridge_ajp', fileExtensions: [".tex",".bib"] },
  { id: 'cambridge_cj', label: 'Can J Math', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Canadian J. Mathematics.', publisher: 'Cambridge', assetFolder: 'cambridge_cj', fileExtensions: [".tex",".bib"] },
  { id: 'cambridge_psa', label: 'Prob Eng Sci', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Probability in the Engineering Sciences.', publisher: 'Cambridge', assetFolder: 'cambridge_psa', fileExtensions: [".tex",".bib"] },
  { id: 'cambridge_qj', label: 'Q J Mech', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Quarterly J. Mechanics.', publisher: 'Cambridge', assetFolder: 'cambridge_qj', fileExtensions: [".tex",".bib"] },
  { id: 'oxford_bio', label: 'Bioinformatics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Bioinformatics.', publisher: 'Oxford', assetFolder: 'oxford_bio', fileExtensions: [".tex",".bib"] },
  { id: 'oxford_biosci', label: 'Biostatistics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Biostatistics.', publisher: 'Oxford', assetFolder: 'oxford_biosci', fileExtensions: [".tex",".bib"] },
  { id: 'oxford_jle', label: 'J Legal Studies', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Legal Studies.', publisher: 'Oxford', assetFolder: 'oxford_jle', fileExtensions: [".tex",".bib"] },
  { id: 'oxford_teb', label: 'Tissue Eng B', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Tissue Engineering B.', publisher: 'Oxford', assetFolder: 'oxford_teb', fileExtensions: [".tex",".bib"] },
  { id: 'tf_aas', label: 'Acta Astronautica', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Acta Astronautica.', publisher: 'Taylor & Francis', assetFolder: 'tf_aas', fileExtensions: [".tex",".bib"] },
  { id: 'tf_ct', label: 'Commun Stat', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Communications in Statistics.', publisher: 'Taylor & Francis', assetFolder: 'tf_ct', fileExtensions: [".tex",".bib"] },
  { id: 'tf_ijp', label: 'Int J Parallel Prog', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Int. J. Parallel Programming.', publisher: 'Taylor & Francis', assetFolder: 'tf_ijp', fileExtensions: [".tex",".bib"] },
  { id: 'tf_jam', label: 'J Appl Math', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Applied Mathematics.', publisher: 'Taylor & Francis', assetFolder: 'tf_jam', fileExtensions: [".tex",".bib"] },
  { id: 'tf_jct', label: 'J Comput Theor Transport', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Computational and Theoretical Transport.', publisher: 'Taylor & Francis', assetFolder: 'tf_jct', fileExtensions: [".tex",".bib"] },
  { id: 'tf_jds', label: 'J Dual Diagnosis', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Dual Diagnosis.', publisher: 'Taylor & Francis', assetFolder: 'tf_jds', fileExtensions: [".tex",".bib"] },
  { id: 'tf_jgm', label: 'J Geometric Mech', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Geometric Mechanics.', publisher: 'Taylor & Francis', assetFolder: 'tf_jgm', fileExtensions: [".tex",".bib"] },
  { id: 'tf_jte', label: 'J Tech Education', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'J. Technology Education.', publisher: 'Taylor & Francis', assetFolder: 'tf_jte', fileExtensions: [".tex",".bib"] },
  { id: 'tf_mcs', label: 'Math Comput Simulation', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Mathematics and Computers in Simulation.', publisher: 'Taylor & Francis', assetFolder: 'tf_mcs', fileExtensions: [".tex",".bib"] },
  { id: 'tf_npb', label: 'Nonlinear Proc Geophys', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'Nonlinear Processes in Geophysics.', publisher: 'Taylor & Francis', assetFolder: 'tf_npb', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_applsci', label: 'Applied Sciences', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Applied Sciences.', publisher: 'MDPI', assetFolder: 'mdpi_applsci', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_arts', label: 'Arts', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Arts.', publisher: 'MDPI', assetFolder: 'mdpi_arts', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_atmos', label: 'Atmosphere', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Atmosphere.', publisher: 'MDPI', assetFolder: 'mdpi_atmos', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_biology', label: 'Biology', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Biology.', publisher: 'MDPI', assetFolder: 'mdpi_biology', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_biomedicines', label: 'Biomedicines', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Biomedicines.', publisher: 'MDPI', assetFolder: 'mdpi_biomedicines', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_buildings', label: 'Buildings', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Buildings.', publisher: 'MDPI', assetFolder: 'mdpi_buildings', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_cancers', label: 'Cancers', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Cancers.', publisher: 'MDPI', assetFolder: 'mdpi_cancers', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_catalysts', label: 'Catalysts', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Catalysts.', publisher: 'MDPI', assetFolder: 'mdpi_catalysts', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_cells', label: 'Cells', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Cells.', publisher: 'MDPI', assetFolder: 'mdpi_cells', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_chem', label: 'Chemistry', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Chemistry.', publisher: 'MDPI', assetFolder: 'mdpi_chem', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_coatings', label: 'Coatings', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Coatings.', publisher: 'MDPI', assetFolder: 'mdpi_coatings', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_computers', label: 'Computers', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Computers.', publisher: 'MDPI', assetFolder: 'mdpi_computers', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_diagnostics', label: 'Diagnostics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Diagnostics.', publisher: 'MDPI', assetFolder: 'mdpi_diagnostics', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_drones', label: 'Drones', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Drones.', publisher: 'MDPI', assetFolder: 'mdpi_drones', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_electronics', label: 'Electronics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Electronics.', publisher: 'MDPI', assetFolder: 'mdpi_electronics', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_energies', label: 'Energies', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Energies.', publisher: 'MDPI', assetFolder: 'mdpi_energies', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_environments', label: 'Environments', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Environments.', publisher: 'MDPI', assetFolder: 'mdpi_environments', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_fibers', label: 'Fibers', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Fibers.', publisher: 'MDPI', assetFolder: 'mdpi_fibers', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_foods', label: 'Foods', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Foods.', publisher: 'MDPI', assetFolder: 'mdpi_foods', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_forests', label: 'Forests', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Forests.', publisher: 'MDPI', assetFolder: 'mdpi_forests', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_fuels', label: 'Fuels', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Fuels.', publisher: 'MDPI', assetFolder: 'mdpi_fuels', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_galaxies', label: 'Galaxies', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Galaxies.', publisher: 'MDPI', assetFolder: 'mdpi_galaxies', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_genes', label: 'Genes', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Genes.', publisher: 'MDPI', assetFolder: 'mdpi_genes', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_healthcare', label: 'Healthcare', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Healthcare.', publisher: 'MDPI', assetFolder: 'mdpi_healthcare', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_inventions', label: 'Inventions', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Inventions.', publisher: 'MDPI', assetFolder: 'mdpi_inventions', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_jcm', label: 'J Clin Medicine', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI J. Clinical Medicine.', publisher: 'MDPI', assetFolder: 'mdpi_jcm', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_lubricants', label: 'Lubricants', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Lubricants.', publisher: 'MDPI', assetFolder: 'mdpi_lubricants', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_machines', label: 'Machines', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Machines.', publisher: 'MDPI', assetFolder: 'mdpi_machines', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_magnetochemistry', label: 'Magnetochemistry', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Magnetochemistry.', publisher: 'MDPI', assetFolder: 'mdpi_magnetochemistry', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_marinedrugs', label: 'Marine Drugs', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Marine Drugs.', publisher: 'MDPI', assetFolder: 'mdpi_marinedrugs', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_materials', label: 'Materials', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Materials.', publisher: 'MDPI', assetFolder: 'mdpi_materials', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_maths', label: 'Mathematics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Mathematics.', publisher: 'MDPI', assetFolder: 'mdpi_maths', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_medicines', label: 'Medicines', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Medicines.', publisher: 'MDPI', assetFolder: 'mdpi_medicines', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_membranes', label: 'Membranes', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Membranes.', publisher: 'MDPI', assetFolder: 'mdpi_membranes', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_microorganisms', label: 'Microorganisms', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Microorganisms.', publisher: 'MDPI', assetFolder: 'mdpi_microorganisms', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_minerals', label: 'Minerals', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Minerals.', publisher: 'MDPI', assetFolder: 'mdpi_minerals', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_molecules', label: 'Molecules', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Molecules.', publisher: 'MDPI', assetFolder: 'mdpi_molecules', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_nano', label: 'Nanomaterials', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Nanomaterials.', publisher: 'MDPI', assetFolder: 'mdpi_nano', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_nutrients', label: 'Nutrients', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Nutrients.', publisher: 'MDPI', assetFolder: 'mdpi_nutrients', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_pathogens', label: 'Pathogens', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Pathogens.', publisher: 'MDPI', assetFolder: 'mdpi_pathogens', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_pharmaceuticals', label: 'Pharmaceuticals', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Pharmaceuticals.', publisher: 'MDPI', assetFolder: 'mdpi_pharmaceuticals', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_pharmaceutics', label: 'Pharmaceutics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Pharmaceutics.', publisher: 'MDPI', assetFolder: 'mdpi_pharmaceutics', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_pharmacy', label: 'Pharmacy', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Pharmacy.', publisher: 'MDPI', assetFolder: 'mdpi_pharmacy', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_photonics', label: 'Photonics', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Photonics.', publisher: 'MDPI', assetFolder: 'mdpi_photonics', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_plants', label: 'Plants', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Plants.', publisher: 'MDPI', assetFolder: 'mdpi_plants', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_polymers', label: 'Polymers', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Polymers.', publisher: 'MDPI', assetFolder: 'mdpi_polymers', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_proteomes', label: 'Proteomes', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Proteomes.', publisher: 'MDPI', assetFolder: 'mdpi_proteomes', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_resources', label: 'Resources', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Resources.', publisher: 'MDPI', assetFolder: 'mdpi_resources', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_sensors', label: 'Sensors', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Sensors.', publisher: 'MDPI', assetFolder: 'mdpi_sensors', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_sports', label: 'Sports', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Sports.', publisher: 'MDPI', assetFolder: 'mdpi_sports', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_sustainability', label: 'Sustainability', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Sustainability.', publisher: 'MDPI', assetFolder: 'mdpi_sustainability', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_symmetry', label: 'Symmetry', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Symmetry.', publisher: 'MDPI', assetFolder: 'mdpi_symmetry', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_toxins', label: 'Toxins', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Toxins.', publisher: 'MDPI', assetFolder: 'mdpi_toxins', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_universe', label: 'Universe', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Universe.', publisher: 'MDPI', assetFolder: 'mdpi_universe', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_vetsci', label: 'Veterinary Sciences', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Veterinary Sciences.', publisher: 'MDPI', assetFolder: 'mdpi_vetsci', fileExtensions: [".tex",".bib"] },
  { id: 'mdpi_water', label: 'Water', icon: '📄', category: 'Journal', subCategory: 'General', desc: 'MDPI Water.', publisher: 'MDPI', assetFolder: 'mdpi_water', fileExtensions: [".tex",".bib"] },
  { id: 'conf_aaai', label: 'AAAI', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'AAAI Conference on AI.', publisher: 'AAAI', assetFolder: 'conf_aaai', fileExtensions: [".tex",".bib"] },
  { id: 'conf_aistats', label: 'AISTATS', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'AI and Statistics.', publisher: 'AISTATS', assetFolder: 'conf_aistats', fileExtensions: [".tex",".bib"] },
  { id: 'conf_asplos', label: 'ASPLOS', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Architectural Support for Programming Languages.', publisher: 'ACM', assetFolder: 'conf_asplos', fileExtensions: [".tex",".bib"] },
  { id: 'conf_chi', label: 'CHI', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Human Factors in Computing Systems.', publisher: 'ACM', assetFolder: 'conf_chi', fileExtensions: [".tex",".bib"] },
  { id: 'conf_cikm', label: 'CIKM', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Information and Knowledge Management.', publisher: 'ACM', assetFolder: 'conf_cikm', fileExtensions: [".tex",".bib"] },
  { id: 'conf_colt', label: 'COLT', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Computational Learning Theory.', publisher: 'COLT', assetFolder: 'conf_colt', fileExtensions: [".tex",".bib"] },
  { id: 'conf_coling', label: 'COLING', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Computational Linguistics.', publisher: 'ACL', assetFolder: 'conf_coling', fileExtensions: [".tex",".bib"] },
  { id: 'conf_dac', label: 'DAC', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Design Automation Conference.', publisher: 'ACM', assetFolder: 'conf_dac', fileExtensions: [".tex",".bib"] },
  { id: 'conf_dsn', label: 'DSN', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Dependable Systems and Networks.', publisher: 'IEEE', assetFolder: 'conf_dsn', fileExtensions: [".tex",".bib"] },
  { id: 'conf_ecai', label: 'ECAI', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'European Conference on AI.', publisher: 'ECAI', assetFolder: 'conf_ecai', fileExtensions: [".tex",".bib"] },
  { id: 'conf_ecml', label: 'ECML PKDD', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'European Conf. on ML and PKDD.', publisher: 'Springer', assetFolder: 'conf_ecml', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'conf_eccv', label: 'ECCV', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'European Conference on Computer Vision.', publisher: 'Springer', assetFolder: 'conf_eccv', fileExtensions: [".tex",".bib",".bst"] },
  { id: 'conf_fse', label: 'FSE', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Foundations of Software Engineering.', publisher: 'ACM', assetFolder: 'conf_fse', fileExtensions: [".tex",".bib"] },
  { id: 'conf_ijcai', label: 'IJCAI', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Int. Joint Conference on AI.', publisher: 'IJCAI', assetFolder: 'conf_ijcai', fileExtensions: [".tex",".bib"] },
  { id: 'conf_kdd', label: 'KDD', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Knowledge Discovery and Data Mining.', publisher: 'ACM', assetFolder: 'conf_kdd', fileExtensions: [".tex",".bib"] },
  { id: 'conf_naacl', label: 'NAACL', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'North American ACL.', publisher: 'ACL', assetFolder: 'conf_naacl', fileExtensions: [".tex",".bib"] },
  { id: 'conf_pldi', label: 'PLDI', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Programming Language Design.', publisher: 'ACM', assetFolder: 'conf_pldi', fileExtensions: [".tex",".bib"] },
  { id: 'conf_popl', label: 'POPL', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Principles of Programming Languages.', publisher: 'ACM', assetFolder: 'conf_popl', fileExtensions: [".tex",".bib"] },
  { id: 'conf_sigcomm', label: 'SIGCOMM', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Data Communication.', publisher: 'ACM', assetFolder: 'conf_sigcomm', fileExtensions: [".tex",".bib"] },
  { id: 'conf_sigir', label: 'SIGIR', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Information Retrieval.', publisher: 'ACM', assetFolder: 'conf_sigir', fileExtensions: [".tex",".bib"] },
  { id: 'conf_sigmod', label: 'SIGMOD', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Data Management.', publisher: 'ACM', assetFolder: 'conf_sigmod', fileExtensions: [".tex",".bib"] },
  { id: 'conf_soda', label: 'SODA', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Discrete Algorithms.', publisher: 'SIAM', assetFolder: 'conf_soda', fileExtensions: [".tex",".bib"] },
  { id: 'conf_sosp', label: 'SOSP', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Operating Systems Principles.', publisher: 'ACM', assetFolder: 'conf_sosp', fileExtensions: [".tex",".bib"] },
  { id: 'conf_www', label: 'WWW', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'World Wide Web Conference.', publisher: 'ACM', assetFolder: 'conf_www', fileExtensions: [".tex",".bib"] },
  { id: 'conf_wsdm', label: 'WSDM', icon: '📄', category: 'Conference', subCategory: 'General', desc: 'Web Search and Data Mining.', publisher: 'ACM', assetFolder: 'conf_wsdm', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_berkeley', label: 'UC Berkeley', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'UC Berkeley Dissertation.', publisher: 'UC Berkeley', assetFolder: 'thesis_berkeley', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_caltech', label: 'Caltech', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'Caltech Thesis.', publisher: 'Caltech', assetFolder: 'thesis_caltech', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_chicago', label: 'U Chicago', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'U. Chicago Dissertation.', publisher: 'U. Chicago', assetFolder: 'thesis_chicago', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_columbia', label: 'Columbia', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'Columbia University Dissertation.', publisher: 'Columbia', assetFolder: 'thesis_columbia', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_cornell', label: 'Cornell', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'Cornell Thesis.', publisher: 'Cornell', assetFolder: 'thesis_cornell', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_georgia', label: 'Georgia Tech', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'Georgia Tech Thesis.', publisher: 'Georgia Tech', assetFolder: 'thesis_georgia', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_harvard', label: 'Harvard', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'Harvard Dissertation.', publisher: 'Harvard', assetFolder: 'thesis_harvard', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_illinois', label: 'UIUC', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'UIUC Thesis.', publisher: 'UIUC', assetFolder: 'thesis_illinois', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_michigan', label: 'U Michigan', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'U. Michigan Dissertation.', publisher: 'U. Michigan', assetFolder: 'thesis_michigan', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_nyu', label: 'NYU', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'NYU Dissertation.', publisher: 'NYU', assetFolder: 'thesis_nyu', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_penn', label: 'UPenn', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'UPenn Dissertation.', publisher: 'UPenn', assetFolder: 'thesis_penn', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_princeton', label: 'Princeton', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'Princeton Thesis.', publisher: 'Princeton', assetFolder: 'thesis_princeton', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_purdue', label: 'Purdue', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'Purdue Thesis.', publisher: 'Purdue', assetFolder: 'thesis_purdue', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_tamu', label: 'Texas A&M', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'Texas A&M Thesis.', publisher: 'Texas A&M', assetFolder: 'thesis_tamu', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_utexas', label: 'UT Austin', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'UT Austin Dissertation.', publisher: 'UT Austin', assetFolder: 'thesis_utexas', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_washington', label: 'UW', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'UW Thesis.', publisher: 'UW', assetFolder: 'thesis_washington', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_wisconsin', label: 'UW Madison', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'UW Madison Thesis.', publisher: 'UW Madison', assetFolder: 'thesis_wisconsin', fileExtensions: [".tex",".bib"] },
  { id: 'thesis_yale', label: 'Yale', icon: '📄', category: 'Thesis', subCategory: 'Global', desc: 'Yale Dissertation.', publisher: 'Yale', assetFolder: 'thesis_yale', fileExtensions: [".tex",".bib"] },
];

export function getTemplateById(id: string) {
  return TEMPLATE_REGISTRY.find(t => t.id === id);
}

export function mapLegacyTemplateId(id: string): string {
  const map: Record<string, string> = {
    't1': 'ieee_tpami',
    't2': 'acm_cacm',
    't3': 'elsevier_ai',
    't4': 'springer_ml',
    't5': 'plos_one',
    't6': 'scirep'
  };
  return map[id] || id;
}
